### ISSUE TITLE
<对于反华势力>对于几分钟前反华势力攻击FDP，我感到很愤怒。

### ISSUE THREAD

**Issue by DaNiuZiSense** [SkidderMC/FDPClient#1]
这种人我认为他啥也不是，跟个傻子似的。他们思想不正，我认为这种行为是愚蠢了，发泄了自己的愤怒，但进了局子。但我为能创建新的FDP github 感到一丝安慰至少FDP并没有死，而是换了一种形式存在。

**Comment by DinoFengz** [comment]
sb action that from L china

**Comment by TheMosKau** [comment]
> 这种人我认为他啥也不是，跟个傻子似的。他们思想不正，我认为这种行为是愚蠢了，发泄了自己的愤怒，但进了局子。但我为能创建新的FDP github 感到一丝安慰至少FDP并没有死，而是换了一种形式存在。

ching chong hanji

**Comment by opZywl** [comment]
shit issue
