### ISSUE TITLE
example issue

### ISSUE THREAD

**Issue by gatooooooo** [SkidderMC/FDPClient#10]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
fdp crashes when trying to run it on a nuclear submarine! exit code 69

**To Reproduce**
1. join the navy 
2. install fdp client on a nuclear submarine
3. start fdp
4. crash!

**Expected behavior**
fdp should let you bhop on the fishes!

**Screenshots/Video**

![submarine](https://user-images.githubusercontent.com/105464811/177673237-35a00164-0fc8-416d-88c0-7e96ca5f8a16.jpg)
(please use actual Screenshots)

**Crash Report**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (FDPClient-6.9.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 15/01/22 10:12
Description: no clue

java.skid.NuclearSubmarineError: fishes to big
                            at java.fdp.submarine(submarine.java:420)
                            -
                            -
                            - // dont stop here xd its just an example

**System Information**
 - OS: submarine os
 - Minecraft Version: submarine forge 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 6.9

**Other Installed Mods**
optifine m6.jar
us navy.jar

**Additional info**
do not take this seriously it is an example

**Comment by C00LC0D35** [comment]
would also be good to include config, hud, blickgui, and the general fdp cluntet folder in the bug reprot as well if its a configs issue

**Comment by TheMosKau** [comment]
![watermark-7](https://user-images.githubusercontent.com/77763580/191765465-1558eb6b-cc66-4f90-9300-337d5b2ad2bb.jpg)

**Comment by Apple26j1** [comment]
> ![watermark-7](https://user-images.githubusercontent.com/77763580/191765465-1558eb6b-cc66-4f90-9300-337d5b2ad2bb.jpg)

lol

**Comment by TheMosKau** [comment]
no

**Comment by gatooooooo** [comment]
closed

**Comment by KOFTWAR** [comment]
lmao

**Comment by DeezFurry** [comment]
hm
