### ISSUE TITLE
[Bug] No hotbar

### ISSUE THREAD

**Issue by Menning4214123** [SkidderMC/FDPClient#1028]
So basically i installed fdp client, but there was no hotbar showing which is pissing me off.

to reproduce,
1. install fdp
2. load it up
3. go into a world
4. BOOM no hotbar !!

There is supposed to be the hotbar, but there isnt.

**Screenshots/Video**
![2023-11-16_21 13 59](https://github.com/SkidderMC/FDPClient/assets/151277014/f3d0ae44-bc47-480d-9857-891caab7752a)

please notice this.

**Comment by Davidisnotavailable** [comment]
enable the hotbar module

**Comment by Menning4214123** [comment]
> enable the hotbar module

thanks.
