### ISSUE TITLE
[Bug] Lag And Crash

### ISSUE THREAD

**Issue by DoubleRainbowXT** [SkidderMC/FDPClient#1041]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
The bug crashes my game everytime for diffrent reasons.
Sometimes times it crashes while loading the mod.
Sometimes it crashes changing settings or going into a server.
And it always crashes when i open clickgui.
I tried minimizing window and even had 10 performence mods install but nothing helped.

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. start minecraft
2. wait
3. go to server
4. open clickgui
5. crash

**Expected behavior**
Work like any other client i use. I have 60 clients that all work fine but this is so darn laggy i get more fps with shaders on max.

**Screenshots/Video**
No it just crashes so not needed

**Crash Report**
Prism launcher dosent give me much info it just says process crashed i looked in .minecraft folder of fdp clients but no crash logs.

**System Information**
 - OS: [Debian Linux]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [all releases]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- I tried it with only fdp and fdp + optifine and fdp + 10 optimazation mods, same problem.

**Comment by ManInMyVan** [comment]
Try with [crash patch](https://modrinth.com/mod/crashpatch)

**Comment by vPrah** [comment]
try with the latest version of fdp
