### ISSUE TITLE
add invate velocity?

### ISSUE THREAD

**Issue by KhanhPhu572** [SkidderMC/FDPClient#1047]
follow this code:
class IntaveVelocity : VelocityMode("Intave") {
    private var velocityInput = false
    private val velocityTimer = MSTimer()

    override fun onUpdate() {
        if (mc.thePlayer.hurtTime > 1 && velocityInput) {
            mc.thePlayer.motionX *= 0.62
            mc.thePlayer.motionZ *= 0.62
        }
        if (velocityInput && (mc.thePlayer.hurtTime < 7 || mc.thePlayer.onGround) && velocityTimer.hasTimePassed(60)) 
            velocityInput = false
    }

    override fun onPacket(event: PacketEvent) {
        val packet = event.packet
        if (packet is S12PacketEntityVelocity) velocityInput = true
    }

**Comment by toidicakhia** [comment]
outdated velo

**Comment by C00LC0D35** [comment]
aac4 red
