### ISSUE TITLE
Some bugs, flaws, bypasses

### ISSUE THREAD

**Issue by rikoshet185** [SkidderMC/FDPClient#1049]
Critical: The crosshair is always on and cannot be disabled
Critical: After adding a new main menu, the optimization in the client became worse. I couldn't play properly before the pc upgrade
Critical: KillESP hides the entire interface when it appears (like F1)
Critical: Autobot does not swap the hotbar to its previous position on the server side
bug: Airjump has a strafe, which makes it flag and be useless
bug: BoatFlys packets are ignored by the server on any version
bug: NCPPacket Fly not bypass NCP
bug: MatrixWater Highjump is not working.
bug: Dolphin jesus works like Legit
bug: MatrixFlag LongJump not bypass, or jumps a very short distance
bug: NCP & NCPDamage longjumps are completely not bypass
bug: FastFall NoWeb completely not working
bug: "OnlySneak" option into Sneak module completely not working
bug: TargetStrafe does not work without speed, even if the "OnlySpeed" option is turned off
bug: AutoPotion with Killaura throws potions at targets, and if you set it up to throw for yourself, then it detects for killaura
bug: The BackTrack may not work
bug: TickBase is not usable
bypass: The Velocity config in the screenshot below can bypass matrix almost without logs
![image](https://github.com/SkidderMC/FDPClient/assets/107861848/30f166cc-54ff-4c05-8401-fd07f0f2c2a3)

bug: MatrixReverse Velocity is not working properly
bug: GroundSpoof Antivoid flags when turned on
bug: Silent AutoTool is not working
bug: AutoGapple it is not synchronized with the movement, which makes it worse on many anti-cheats
bug: "OnlySwordWeapon" in InvManager throws tools even when there is no sword in the inventory, which allows you to remain unarmed
bug: InvManager throws away diamond armor, preferring leather enchanted
bug: MatrixCollide and MatrixNew NoFalls  did not bypass matrix at the time of addition. And they do not absorb the damage from the fall
bug: with Scaffold cannot be built diagonally ( or will it be flagged ) with static rotation
bug: InfiniteDurability completely not working ( tested on 1.8 )
bug: "OnlySneak" into teleport not working with Rewi, Spoof, ААС modes
bug: Verus BHop with speed effect breaks down and bans on ColdNetwork
bug: Jump Step works worse than Autojump
bypass: TargetStrafe without strafe can bypass matrix by boosting from Reverse Velocity
bug: FightBot is not finished yet
bug: InfiniteAura attacks all targets when one is set in the settings
bug: "NoLagback" in InfiniteAura works very buggy, on 1.9+ with this setting you can suddenly be killed
bug: Jello clickgui has no animations when pointing the cursor at the module
bug: Light clickgui is non-clickable in the lower right part, and the sliders are not divided into each of their own bypasses

Flaw: FDP src does not compile with the guide that is on github ( JavaCompileError )

Suggest: "MatrixXD" Jesus mode has deleted, but perfectly bypassed the fast Jesus on Matrix

Suggest: Spam positions, quickly sitting and getting out of the boat, can bypass a lot of anti-cheats (Like the last matrix) to teleport to any coordinates uploaded by the server (Even from 0 ~ 0 to 29999999 ~ 29999999)
Tested with basic spam positions
And HACDisabler

Suggest: AACPort Speed, bypasses all anti-cheats on Alpha and Beta (and Fly on Old NoCheat), and there are a lot of shitty anti-cheats now. I don't understand why it was deleted

**Comment by C00LC0D35** [comment]
config issue

**Comment by rikoshet185** [comment]
updated

**Comment by vPrah** [comment]
Lmao, I will check this

**Comment by vPrah** [comment]
Added AACPort, LightClickGUI is deleted, FDP Compile errors are fixed, scaffold bugs fixed, OnlySneak fixed, Use the new "LatestVerusHop" mode and customize it.
