### ISSUE TITLE
add 1.17 transaction fix to viaversion

### ISSUE THREAD

**Issue by JunStock** [SkidderMC/FDPClient#1071]
`
pls update viafarbic
`

Via follow to fix flag use GrimC07
Changed via base to ViaMCP
1.17 transaction fix

**Comment by toidicakhia** [comment]
omg he's very retard

**Comment by Rylazius** [comment]
no way mf couldnt skid

**Comment by toidicakhia** [comment]
this fix is not necessary, due to viafabricplus fixed.

**Comment by chillingstar** [comment]
💀

**Comment by toidicakhia** [comment]
> `transaction fix code`
> 
> ```
> @@ -44,6 +44,7 @@ public ViaMCP() {
>                 getAsyncVersionSlider().setVersion(comparableProtocolVersion.getVersion());
>             }
>         }).build();
>         fixTransactions();
>     }
> 
>     private void fixTransactions() {
> ```
> 
> Via follow to fix flag use GrimC07 Changed via base to ViaMCP 1.17 transaction fix

wtf skidded from minusbounce????

**Comment by KhanhPhu572** [comment]
> viafabricplus fixed

real?

**Comment by FyxarDev** [comment]
> this fix is not necessary, because viafabricplus fixed. :trollface:

nah actually in 1.17+ there is not issues with transaction so if u backported viafabricplus for 1.8 then you still need the fix.

**Comment by LongAthelstan** [comment]
omg RIP

**Comment by vPrah** [comment]
Updated and fixed
