### ISSUE TITLE
[Bug] <fdp崩溃>

### ISSUE THREAD

**Issue by jerryyudev** [SkidderMC/FDPClient#1072]
当我在fdp客户端时卡中文输入法时，fdp的所有功能被开启，并且客户端崩溃

**Comment by tjshtqwq** [comment]
请说英文，要不他们看不懂
plz English

**Comment by tjshtqwq** [comment]
我也这样......
Me too

**Comment by NewbieMX1314** [comment]
因为输入中文才有的吗？我还以为按到啥按键了
caz of Chinese char?i just think i press some key to enabled it lol

**Comment by tjshtqwq** [comment]
是的，高版本FDP抽风
fk fdp

**Comment by NewbieMX1314** [comment]
***5.4.0以后的版本*都有**
> Appear after all version after 5.4.0

**Comment by jerryyudev** [comment]
只要你在启用中文输入法的情况下在游戏中按下w键，所有功能都会被启用，客户端很快会崩溃
As soon as you press the w key in the game with the Chinese input method enabled, all features will be enabled and the client will soon crash

**Comment by NewbieMX1314** [comment]
不一定是w  鍵

我的不会崩溃，但是会打开大部分modules，并且会暂时卡顿1分钟
随后就会白屏（但好像是cham&glowesp等同时开启出现的）
在5.4.0以及以上的版本，我游玩pika或jartex服务器时会ui错位（也可能不是中文输入的问题）

我降级到fdp5.3.5后这些问题基本消失


> *no probably `"w" `keys*
> My fdp client won't **crash,**but it will* open many modules* and *lag some time*
> Then will be **White screen (also red screen and green screen)**(`It may be a problem that cham and glowesp module are open at the same time.`)
> *Above* fdp *ver.5 4 0,*when i play pika/jartex network , my ui will be **misplaced**.*(maybe not about input problem)*
> The problem *basically* disappeared when I `downgraded` to **version 5.3.5.**

**Comment by Revethere** [comment]
不止这些情况 .

在笔记本上用 Fn + 其它按键时也会导致所有功能开启 awa

**Comment by shuimu5418** [comment]
为longjump设置一个模式。试试看。
