### ISSUE TITLE
[Bug] <?>

### ISSUE THREAD

**Issue by NewbieMX1314** [SkidderMC/FDPClient#1079]
![javaw_bRA6DJ3Kad](https://github.com/SkidderMC/FDPClient/assets/120234905/bea53280-943b-478c-afa6-5598a0c32fcb)
![javaw_xrSzVYPLP3](https://github.com/SkidderMC/FDPClient/assets/120234905/b8adc2bd-c111-4807-993d-0d4d3832ddd4)
sometime when i join ***pika** or **jartex*** server will have this problem
> but other server havenot
i tried *3 version* all will have this problem
just at some minigames server will *appear*
is that my problem
?

**Comment by jerryyudev** [comment]
I often play on these servers, but nothing like this happens.

**Comment by NewbieMX1314** [comment]
> I often play on these servers, but nothing like this happens.

Um
What fdp ver u using?

**Comment by PrahXZ** [comment]
Delete the root folder of FDPCLIENT in your .minecraft and try again.
