### ISSUE TITLE
fdp lags, crashes and dont work] <Title Here> fdp lags, crashes and dont work

### ISSUE THREAD

**Issue by rayosalkae** [SkidderMC/FDPClient#1082]
today i installed it, i put it in my mods folder for forge 1.8.9, then i opened it and when i opened it it was jerking (i have a good pc with 32gb ram and a ryzen 5600g processor) it was going at 10 fps and i dont understand how that happened, i checked that only happened to me with the fdp, i want a solution please.

**Comment by opZywl** [comment]
Hi, I'm sorry you're having trouble starting FDP. I ask you to please provide us with your crash report. so we can see what's going on

**Comment by rayosalkae** [comment]
fdp freezes for a few moments, then thaws, refreezes, and crashes.

**Comment by C00LC0D35** [comment]
wow nice crash report

**Comment by vPrah** [comment]
without a crash report, i cant help you
