### ISSUE TITLE
[Bug] <REMOVE THIS FUCKING THING!!!11>

### ISSUE THREAD

**Issue by UnSovieticoXD** [SkidderMC/FDPClient#1097]
PRESS FN + F7 OR F8 AND SEE WHATS HAPPENING OMG!!!!1!!1

**Comment by PrahXZ** [comment]
Te voy a responder en español, basicamente todo el sistema de binds esta bugeado por culpa de Zywl y sus actualizaciones raras 👍

**Comment by C00LC0D35** [comment]
then dont press f7...
