### ISSUE TITLE
[Bug] Font is broken

### ISSUE THREAD

**Issue by contionability** [SkidderMC/FDPClient#11]
Fonts are not rendering properly (blank)
@opZywl

**Comment by TheMosKau** [comment]
%ui.chest.stealing%

**Comment by dennychan666** [comment]
%ui.chest.stealing% 
what is this ?

**Comment by fdpmc** [comment]
> %ui.chest.stealing%


i fixed this in my fork fdp classic
https://github.com/fdpclassic/FDPClassic/commit/3ae2e3463b20a321dddbfed539d39e6d485d07be
it is because someone removed the lang thing to add fu***ng shadows xd

**Comment by RealPacket** [comment]
> > %ui.chest.stealing%
> 
> i fixed this in my fork fdp classic [fdpclassic/FDPClassic@3ae2e34](https://github.com/fdpclassic/FDPClassic/commit/3ae2e3463b20a321dddbfed539d39e6d485d07be) it is because someone removed the lang thing to add fucking shadows xd
