### ISSUE TITLE
backtrack instaban + lag

### ISSUE THREAD

**Issue by denijel98765555678** [SkidderMC/FDPClient#1107]
when i turn on backtrack ( with any settings ) on servers where are more people it stratrs to lag and if it is ffa o skywars for example and i try to hit someone i get instantly banned, this is same on every server. It looks something like a spider web, but its just the helping lines for the backtrack get extremly stretch - making you able to hit players while being very far away. Its also very weird because sometimes the lag isnt there but other times it gets even laggy and stuff.

1. Turn on backtrack (to see the lag you ill most likely need to use very hight backtarck settings, but it does occur even with the lowest settings possible)
2. Go on any server with/lobby where is pvp enabled
3.See the white lines ( it think has to do something with the backtrack programme because sometimes everything is ok. It occur the most when players die and get send back to lobby -ffa or hypixel pit- or when they fall or when they sprint in general)

**Expected behavior**
I dont really care about the lines but when i hit someone especially when he has the long white trail behind him i get instantly banned for reach (or any server) which i dont like because the backtrack is really good

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
![2024-03-03_22 13 39](https://github.com/SkidderMC/FDPClient/assets/162059173/3a00f57e-3ffe-40fa-999b-6f5d15a8a868)
i hope you can see it. if not you can replicate it by turning both bactrack options to max and going to any pvp enabled lobby
(hypixel pit, skywars, ffa) - i was trying this on mineberry and bwhub

**System Information**
 - OS: [e.g. Windows 11]
 - Minecraft Version: [1.8.9] + tlauncher
 - Forge Version: [1.8.9-forge1.8.9-11.15.1.2318-1.8.9]
 - FDPClient Version: [v5.5.0 ]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Wavey capes https://www.youtube.com/watch?v=DwiDZ2aJ-ac>
-( OptiFine_1.8.9_HD_U_M5)

**Additional info**
<i have already mentioned it but it occurs only soemtimes (50/50) and CAN be replicated using maximal settings HOWEVER the lag can happen (it did for me) even at minimal settings (backtarck set to 30ms and max loc. to 1) + i maybe didnt mention this but the trail follows the player - same as it would with normal settings- but supersized= i can hit players from crazy distances -i dont want that- making it impossible to closet cheat.>
ok thanks hope you ill find a way to fix this an thanks for this amazing client (100x better than classic liqid)
gl bye

**Comment by C00LC0D35** [comment]
dont use backtrack. use legit reach
