### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by hi-bi-hs-13** [SkidderMC/FDPClient#1109]
![Screenshot (332)](https://github.com/SkidderMC/FDPClient/assets/157794426/5063e9fb-5afc-43b0-8c9e-e6b7b36ede0d)
------------
I need help
(my gmail: amirali13371337@gmail.com(I dont check the github))

**Comment by hi-bi-hs-13** [comment]
I install only fdp client mod
and i use "Legacy Launcher Stable"

**Comment by hi-bi-hs-13** [comment]
when i delete the config default I can run the fdp

**Comment by vPrah** [comment]
Fixed, try it now with the latest commited version
