### ISSUE TITLE
[Bug] longjump

### ISSUE THREAD

**Issue by shuimu5418** [SkidderMC/FDPClient#1111]
**Describe the bug**
The default mode for long jump has not been selected.
This causes extreme lag when the long jump is turned on.
Unfortunately, similar to previous issues, when I press any button (excluding the mouse button), all modules will be turned on. This caused me to crash the game multiple times in order to troubleshoot the problem.
**To Reproduce**
1. Start the game 
2. join a world
3. press any key
4. all the modules are turned on (game lag)
5. turn off modules one by one(crazy experience)
6. when i turned off longjump, the lag was immediately significantly reduced
7. i found the mode of longjump was unselected.
8. turned it on, the game laaaaaaaaaaaaag and then i turned longjump off
9. select a mode for longjump, and turn it on
10. no lag
11. close game, try steps 1, 2, and 3 again, nothing happened, game working well
12. delete cfg.json ,try steps 1, 2, and 3 again, the thing same to 4 happened!

**Expected behavior**
have fun

**System Information**
 - OS: Windows 11
 - Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 5.5.0

**Other Installed Mods**
none

**Additional info**
none

**Comment by C00LC0D35** [comment]
Thank you
