### ISSUE TITLE
very laggy

### ISSUE THREAD

**Issue by JunStock** [SkidderMC/FDPClient#1112]
Using fdp client is very laggy (windows 11 operating system)
under 60 fps
my pc configuration (playing under 60fps)
![Untitled](https://github.com/SkidderMC/FDPClient/assets/146457695/37903f9c-4457-4ff4-8749-ae498e4cc6cb)

**Comment by dudethis** [comment]
is your cpu underclocked?

**Comment by vPrah** [comment]
try enabling Performance and MemoryFix modules
