### ISSUE TITLE
FDP CLIENT CRASH ERROR

### ISSUE THREAD

**Issue by BISHOPLOL9** [SkidderMC/FDPClient#1122]
![image](https://github.com/SkidderMC/FDPClient/assets/154857447/1f796590-3866-49cd-99ca-fd59dae333fe)

**Comment by vPrah** [comment]
try it with the latest version, i think it has been fixed.

**Comment by vPrah** [comment]
and remove your root folder of "FDPClient"

**Comment by vPrah** [comment]
you are welcome
