### ISSUE TITLE
[Bug] Pojavlaucher When entering the beta versions, the phone freezes

### ISSUE THREAD

**Issue by unlimitedlinux** [SkidderMC/FDPClient#1124]
I have played the beta versions of fdp and after entering the latest beta version, halfway through loading modules the phone freezes, I have to spam the buttons on both sides before I can restart, please fix it.

**Comment by unlimitedlinux** [comment]
start optmized it lags on pojavlaucher device

**Comment by opZywl** [comment]
Sorry, we don't directly support Pojav Launcher.

**Comment by C00LC0D35** [comment]
do you know what module the phone freezes on?

**Comment by VeensCal** [comment]
You can still use fdp 5.5.0

**Comment by vPrah** [comment]
We dont directly support Pojav Launcher, try using use fdp 5.5.0 😊

**Comment by VeensCal** [comment]
When are u gonna update it 5.6.0.1

**Comment by VeensCal** [comment]
When will FDP client update maybe next hotfix

**Comment by VeensCal** [comment]
For pojav support
