### ISSUE TITLE
5.5.0 no download link

### ISSUE THREAD

**Issue by NetworkHeck** [SkidderMC/FDPClient#1127]
Okay so I wanted to download FDP CLIENT 5.5.0 not the betas when I wanted to download it was a zip I extracted I got a folder with the client folders not the jar so I got the original zip and changed it to jar and put it in mods and it did not recognize it as mod once I loaded mc help!!

**Comment by Cup4Cake4Guy** [comment]
I think you might have to compile it yourself using Gradle or something...

**Comment by alexplaysminecraft** [comment]
well it the devs job

**Comment by opZywl** [comment]
Hi brothers, fixed try again

**Comment by NetworkHeck** [comment]
Thanks alot

**Comment by NetworkHeck** [comment]
> I think you might have to compile it yourself using Gradle or something...

How tho? And what is gradle

**Comment by C00LC0D35** [comment]
Go to actions, click on a commit, go to artifacts (scroll down) and download the file. We fix leter

**Comment by NetworkHeck** [comment]
Omgg thankssss alot!!
