### ISSUE TITLE
FDP Client Crashing

### ISSUE THREAD

**Issue by Cup4Cake4Guy** [SkidderMC/FDPClient#1128]
### FDP CLIENT CRASH

[crash-2024-03-30_20.10.06-client.txt](https://github.com/SkidderMC/FDPClient/files/14812355/crash-2024-03-30_20.10.06-client.txt)
I'm using **ATLauncher** along with **some mods**, they will be listed in the crash report. If I remove FDP Client JAR File and try launching everything works just fine I've tried using these versions of FDP;
**V** **5.3.5**
    &
**V 5.3.0**

but had no luck. I'm hoping that someone here will be able to identify the issue and help me resolve it.

**Comment by alexplaysminecraft** [comment]
well for me beta doesnt work it js bugged the fuck out

**Comment by Cup4Cake4Guy** [comment]
I am not using any Beta versions I am suing the versions of FDP released on this GitHub Page

**Comment by vPrah** [comment]
Use latest beta version in commit > actions > download artifacts
