### ISSUE TITLE
Targetstrafe module is broken

### ISSUE THREAD

**Issue by ZHYUjun** [SkidderMC/FDPClient#1129]
it does not work with any option disabled or enabled, toggling speed doesn't help either, the client just refused to let me strafe in circle toward my opponent, im pretty sure there's nothing wrong with my config since it works in older release versions, but stopped working on the latest nightly version

**Comment by C00LC0D35** [comment]
zywl fucked a mixin up, sorry, check back tmrw for fix, use 5 old commits
