### ISSUE TITLE
[Bug] Crash when loading a config

### ISSUE THREAD

**Issue by Reycko** [SkidderMC/FDPClient#1135]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Crashing when uploading a config.

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Launch MC
2. Go to BlocksMC
3. Load [this config](https://pastebin.com/raw/x0Ak6KNM)
4. Crash

**Expected behavior**
The config loading successfully.

**Screenshots/Video**
![image](https://github.com/SkidderMC/FDPClient/assets/78082869/0ab2d312-ac46-469d-9951-37a87b6ef58c)

**Crash Report**
[Uploaded it on mclo.gs](https://mclo.gs/WBu6Bkt)

```text
[Paste Here]
```

**System Information**
 - OS: Windows 11 (10.0.22631.3374)
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 5.6.0

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
N/A

**Additional info**

**Comment by opZywl** [comment]
delete you fdp folder and try again

**Comment by Reycko** [comment]
> delete you fdp folder and try again

Just tried it, still having the same crash happen

**Comment by Reycko** [comment]
Hotfix fixed my issue
