### ISSUE TITLE
fdp crashes when opening the clickgui

### ISSUE THREAD

**Issue by rediamond232** [SkidderMC/FDPClient#1140]
**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. launch the game
2. open the clickgui

**Expected behavior**
crash

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
<img width="1110" alt="Screenshot 2024-04-06 at 10 27 26" src="https://github.com/SkidderMC/FDPClient/assets/134283342/a33152fa-c844-4330-a67e-099e14e9e4f3">

```text
[Paste Here]
```

**System Information**
 - OS: [macos]
 - Minecraft Version: [ 1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [5.6.0 latest stable]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- optifine

**Additional info**
i think its a render bug

**Comment by C00LC0D35** [comment]
Which clickgui and do you have fast render on

**Comment by vPrah** [comment]
try with the latest version of fdp (latest commit in actions page)
