### ISSUE TITLE
[Bug] fdp being weird asf

### ISSUE THREAD

**Issue by larryngton** [SkidderMC/FDPClient#1141]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
pausing/playing my music via the keyboard bind enables every fucking module on fdp

**To Reproduce**
1. press the play/pause button
2. funny

**Expected behavior**
it shouldnt toggle every module

**Screenshots/Video**
 .

**Crash Report**
 .

**System Information**
 - OS: win 11
 - Minecraft Version: 1.8
 - Forge Version: latest
 - FDPClient Version: latest hotfix

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
ingame account switcher
rawinput
optifine

**Additional info**
.

**Comment by vPrah** [comment]
We know about this problem but not how to solve it 😔😔

**Comment by Reycko** [comment]
> We know about this problem but not how to solve it 😔😔

Might have something to do with Shift+Numpad5
