### ISSUE TITLE
multiplayer servers crashing

### ISSUE THREAD

**Issue by noxirius** [SkidderMC/FDPClient#1148]
![billede_2024-04-09_094219776](https://github.com/SkidderMC/FDPClient/assets/166486965/c156cd61-1f12-4224-92df-0cd20cec532e)
![Screenshot_20240409_084950](https://github.com/SkidderMC/FDPClient/assets/166486965/aa2be1f7-3e7a-4c09-a946-79fd7ffbb407)
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. joining a multiplayer server
2. i was playing on a multiplayer server and i switched my cape to rose and my game started to freak out then i rejoined and then the error occurred
3. 
4. 

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Error: java.lang.IllegalStateException: glGenLists returned an ID of 0 for a count of 1, GL error (0): No error code reported]
```

**System Information**
 - OS: [Windows 11]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [v5.6.0]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
no other mods

**Additional info**
<.>

**Comment by dg636** [comment]
can you give us the config you were using?

**Comment by noxirius** [comment]
> can you give us the config you were using?

i didnt have any configs on

**Comment by vPrah** [comment]
Try update your graphics card driver
