### ISSUE TITLE
ClickGui style nextgen did not load

### ISSUE THREAD

**Issue by liquidbounce-thebestclient** [SkidderMC/FDPClient#1210]
FDPclient git-38e4ab1 
forge 11.15.1.2318
optfine HD_H_M5
with mod "lagfix" and "chinese input"
java8
no jvm

i open clickgui , and it load style black , i switch it to neverlose or nextgen , but nothing happend 

i try ".clickgui style nextgen "too , not work too

**Comment by ZeathDev** [comment]
they r just ornamental modes
