### ISSUE TITLE
[Bug] white screen

### ISSUE THREAD

**Issue by vantthinkofanameyet** [SkidderMC/FDPClient#1238]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
when entering the client all you get is a white screen no matter what

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. open fdp
2. white screen

**Expected behavior**
fdp would just show up normally

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: android 14 with pojavlauncher
 - Minecraft Version: 1.8.9
 - Forge Version: latest
 - FDPClient Version: b8

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- optifine m6 pre 2

**Additional info**
<Add any other context about the problem here.>

**Comment by opZywl** [comment]
android;-;

**Comment by vantthinkofanameyet** [comment]
ive seen someone use b7 on pojavlauncher (https://youtu.be/0vtNwAjqJgo?si=lEfgk2yxW120MHnP), ive tried b7 too but same thing. also i dont think its a ram issue because ive tried allocating 1500 mb of ram and still got a white screen even without any ram warnings

**Comment by vantthinkofanameyet** [comment]
.

**Comment by opZywl** [comment]
sorry i dont use android/pojav  I have no idea how to help you

**Comment by vantthinkofanameyet** [comment]
fixed
