### ISSUE TITLE
[Bug] <GL4ES Crash>

### ISSUE THREAD

**Issue by ProSteve12301** [SkidderMC/FDPClient#13]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<Exits every time when FDP are initializing.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Launch PojavLauncher
2. Launch Forge
3. Wait
4. And Crash.

**Expected behavior**
<Just Exits.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
![Screenshot_2022-07-06-18-27-58-67_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/79408961/177773814-ddab6a38-c20f-41c0-a7c7-da649957c6de.jpg)

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[crash-2022-07-06_10.26.23-client.txt](https://github.com/SkidderMC/FDPClient/files/9063536/crash-2022-07-06_10.26.23-client.txt)

```

**System Information**
 - OS: Android 9
 - Minecraft Version: 1.8.9
 - Forge Version: Latest
 - FDPClient Version: Latest
 - Launcher: PojavLauncher Latest 1.19

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine 1.8.9

**Additional info**
<Fix it Please :) .>

**Comment by ProSteve12301** [comment]
> Please note that we do not provide support for clients other than Forge. We will not fix compatibility issues with other clients.
> 
> **Describe the bug**
> 
> **To Reproduce** <Steps to reproduce the behavior (how did you get this bug to occur):>
> 
> 1. Launch PojavLauncher
> 2. Launch Forge
> 3. Wait
> 4. And Crash.
> 
> **Expected behavior**
> 
> **Screenshots/Video** If applicable, add screenshots, or a video to help explain your problem. ![Screenshot_2022-07-06-18-27-58-67_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/79408961/177773814-ddab6a38-c20f-41c0-a7c7-da649957c6de.jpg)
> 
> **Crash Report** If your game crashed, please paste your crash report below.
> 
> ```
> [crash-2022-07-06_10.26.23-client.txt](https://github.com/SkidderMC/FDPClient/files/9063536/crash-2022-07-06_10.26.23-client.txt)
> ```
> 
> **System Information**
> 
> * OS: Android 9
> * Minecraft Version: 1.8.9
> * Forge Version: Latest
> * FDPClient Version: Latest
> * Launcher: PojavLauncher Latest 1.19
> 
> **Other Installed Mods** If you have any other mods installed, please list them here along with their version number.
> 
> * Optifine 1.8.9
> 
> **Additional info** <Fix it Please :) .>

...
Crash Link
[crash-2022-07-06_10.26.23-client.txt](https://github.com/SkidderMC/FDPClient/files/9063584/crash-2022-07-06_10.26.23-client.txt)

**Comment by DinoFengz** [comment]
pojav bug

**Comment by ProSteve12301** [comment]
> pojav bug

I think you fix it right?
Im so annoy playing blocksmc cuz of staffs.

**Comment by C00LC0D35** [comment]
anti staff exists

**Comment by ProSteve12301** [comment]
![Screenshot_2022-07-08-04-54-23-90_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/79408961/177869790-e37051db-b519-4faa-91dc-4e0472370bff.jpg)
LLLLLLLL

**Comment by ProSteve12301** [comment]
Fixed :)
