### ISSUE TITLE
[Bug]<Font is Broken.PojavLauncher Bug Fixed,Keep it up!!!>

### ISSUE THREAD

**Issue by ProSteve12301** [SkidderMC/FDPClient#18]
Fix Please and Thanks for Fix.Now i can cheat!!!
![Screenshot_2022-07-08-05-07-50-65_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/79408961/177871793-af2bbaf2-d2ef-43fb-bc8d-e5bb3ebdbff0.jpg)

**Comment by ProSteve12301** [comment]
> no

why?

**Comment by Davidisnotavailable** [comment]
Delete special.json file .minecraft -> Fdpclient

**Comment by ProSteve12301** [comment]
Fixed :)
