### ISSUE TITLE
I can't build a successful client #281

### ISSUE THREAD

**Issue by ww123456wwqq** [SkidderMC/FDPClient#20]
When building a client, it is not possible to resolve all dependencies contained in the configuration, the resource "https://repo.getfdp.today/me/liuli/Elixir/1.2.1/Elixir-1.2.1.pom" cannot be obtained https://repo.getfdp.today/me/liuli/Elixir/1.2.1/Elixir-1.2.1.pom received status code 403 from the server: Forbidden

**Comment by contionability** [comment]
you may try again using the latest commit

**Comment by contionability** [comment]
I switched to another repo

**Comment by ww123456wwqq** [comment]
> 您可以使用最新的提交重试

Thanks, it's ready to build.

**Comment by ww123456wwqq** [comment]
> > 您可以使用最新的提交重试
> 
> Thanks, it's ready to build.

Wrong said speechless

**Comment by ww123456wwqq** [comment]
> 您可以使用最新的提交重试

Thanks, the build was successful
