### ISSUE TITLE
PacketFly. Works On Blockdrop bedwars. and mineland bedwars<Title Here>

### ISSUE THREAD

**Issue by Zerolysimin** [SkidderMC/FDPClient#251]
code : 

float yaw = (float) Math.toRadians(mc.player.rotationYaw);
double x = -Math.sin(yaw) * 0.25;
double z = Math.cos(yaw) * 0.25;
mc.thePlayer.connection.sendPacket(new C03PacketPlayer.C04PacketPlayerPosition(mc.player.posX + x, mc.player.posY,
mc.player.posZ + z, false) 
mc.thePlayer.connection.sendPacket(new C03PacketPlayer.C04PacketPlayerPosition(mc.player.posX + x, mc.player.posY - 490,
mc.player.posZ + z, true);

mc.player.motionY = 0;

i cant put mc.player.posZ + z, true); at end of word lol.
also this packetfly is slow. and very basic xdd
ofc i have faster one in mi client

**Comment by Logging4J** [comment]
nice

**Comment by C00LC0D35** [comment]
k
