### ISSUE TITLE
<Matrix fly> it's a script (.js) made by @bilalware on yt. even though it is a script im sure that it can be converted to a .JAVA module

### ISSUE THREAD

**Issue by NerdHax** [SkidderMC/FDPClient#252]
[BW-script.txt](https://github.com/SkidderMC/FDPClient/files/9142831/BW-script.txt)

this is the script (**again the credit goes to Bilalware on youtube for making this**)

also the link to the vid where he shows it off   https://www.youtube.com/watch?v=VnDXgiTuNi8&ab_channel=BilalWare

**Comment by DaNiuZiSense** [comment]
这个只是专门对于老版本的Matrix漏洞 在Matrix6.8.14他没有任何效果
