### ISSUE TITLE
[Bug] <Fdp Client HUD broken and visual glitches when enabled>

### ISSUE THREAD

**Issue by bitchslap** [SkidderMC/FDPClient#258]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<I use the newest version of beta builds and for the past week, all of them had problems with the hud. When I enable hud on a server or something every thing i had created: arraylist, scoreboard, text, images get wiped off the hud, and when i try to open the clickgui, instead of there being a clickgui, theres a black box in the right down corner, sometimes, when hud is enabled, a duplication of the player model appears beneath you.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Get fdp beta build
2. Run the client
4. Join a server
5. Enable hud
6. Everything gets fucked up

**Expected behavior**
<i expected nothing to happen and just load my visuals but everything just gets bugged out and glitches happen with the visuals like summoning white text on the player's characters, or random textures appearing on top of the chest when you loot it.>

**Screenshots/Video**
https://cdn.discordapp.com/attachments/990618560994893834/999587206098321438/unknown.png
https://cdn.discordapp.com/attachments/990618560994893834/999587465977417799/unknown.png
https://cdn.discordapp.com/attachments/990618560994893834/999589667924094976/unknown.png

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [git-562cc28]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Music player 1.8.9>
- <optifine 1.8.9>

**Additional info**
<Add any other context about the problem here.>

**Comment by dudethis** [comment]
I also have this issue.

**Comment by RealPacket** [comment]
you can even do this without any mods lmao

**Comment by C00LC0D35** [comment]
dont use blur is probablywhat i wud recomentd  tyr dat
