### ISSUE TITLE
FDP can't bypass Grim Antiheat

### ISSUE THREAD

**Issue by LineOpng** [SkidderMC/FDPClient#259]
Can't bypass and is free anti-cheat

**Comment by DaNiuZiSense** [comment]
https://github.com/MWHunter/Grim/issues/668

**Comment by LineOpng** [comment]
Velocity noslow Autoblocks lag :(

**Comment by timof121** [comment]
self control

**Comment by DaNiuZiSense** [comment]
@LineOpng  noslow watchdog2 autoblock vanilla bypass

**Comment by LineOpng** [comment]
@DaNiuZiSense  Chinese servers are all matrices, plus Grim Antiheat and other anti-cheats exist, it's GG

**Comment by DaNiuZiSense** [comment]
@LineOpng 对于Matrix和GrimAC的组合 我的选择是直接放弃
