### ISSUE TITLE
Add HWID Spoof<Feature request>

### ISSUE THREAD

**Issue by SmaamX** [SkidderMC/FDPClient#262]

**Comment by timof121** [comment]
please kill

**Comment by timof121** [comment]
![caption-7-2](https://user-images.githubusercontent.com/52547763/180595209-d1fb062f-2e74-4a67-bb5b-91b442a89352.gif)

**Comment by AmoSense** [comment]
> ![caption-7-2](https://user-images.githubusercontent.com/52547763/180595209-d1fb062f-2e74-4a67-bb5b-91b442a89352.gif) [ ![caption-7-2](https://user-images.githubusercontent.com/52547763/180595209-d1fb062f-2e74-4a67-bb5b-91b442a89352.gif) ](https://user-images.githubusercontent.com/52547763/180595209-d1fb062f-2e74-4a67-bb5b-91b442a89352.gif) [ ](https://user-images.githubusercontent.com/52547763/180595209-d1fb062f-2e74-4a67-bb5b-91b442a89352.gif)

keep yourself safe

**Comment by timof121** [comment]
(kill yourself)
