### ISSUE TITLE
< Need > Create Killaura OnlyOnGround to bypass GrimAC

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#263]

**Comment by RealPacket** [comment]
just check if the player is onGround and then continue xd

**Comment by RealPacket** [comment]
something like this:
```
if(mc.thePlayer.isonGround = true) {
      continue;
 {
```

**Comment by timof121** [comment]
```
if (!mc.thePlayer.onGround){
    return;
}

**Comment by RealPacket** [comment]
also an option

**Comment by C00LC0D35** [comment]
use scripts cuz ive never heard of grim so its prob not common also weird asf bypass, so i dwont add :trollface:

**Comment by RealPacket** [comment]
> use scripts cuz I've never heard of grim so its prob not common also weird ASF bypass, so I won't add :trollface:
Don't worry, I'll make the grim AC bypass on my repo :trollface:
