### ISSUE TITLE
[Bug] <Fix World Render Crash(PojavLauncher)>

### ISSUE THREAD

**Issue by ProSteve12301** [SkidderMC/FDPClient#27]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<While testing an config,my game are freezed and exits.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Launch PojavLauncher
2. Launch Forge
3. Play SinglePlayer or Multiplayer
4. Crash!!!

**Expected behavior**
<Exits Only.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

`Sorry no screenshot.`

**Crash Report**
If your game crashed, please paste your crash report below.

```text
File Below 👇
```
[crash-2022-07-08_20.50.41-client.txt](https://github.com/SkidderMC/FDPClient/files/9076452/crash-2022-07-08_20.50.41-client.txt)

**System Information**
 - OS: Android 9(ofc)
 - Minecraft Version: 1.8.9
 - Forge Version: Latest
 - FDPClient Version: Latest Action

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine 1.8.9

**Additional info**
<Fix it please :) .>

**Comment by DinoFengz** [comment]
@gatooooooo

**Comment by DinoFengz** [comment]
array list bug uh

**Comment by ProSteve12301** [comment]
My Pojav doesnt support shiny visuals.

**Comment by ProSteve12301** [comment]
Fixed
