### ISSUE TITLE
Not bypassing Grim 

### ISSUE THREAD

**Issue by LineOpng** [SkidderMC/FDPClient#272]
killaura Velocity Speed Sprint noslow lag

**Comment by LineOpng** [comment]
Free Anti-Cheat to End FDP

**Comment by LineOpng** [comment]
Not bypassing Grim

**Comment by MatrixU5er** [comment]
What's the significance of this anti cheating superposition? FDP only focuses on a certain anti cheating bypass rather than superposition anti cheating

**Comment by LineOpng** [comment]
@MatrixU5er We need Grim bypass mode

**Comment by ReCaree** [comment]
what do you mean? matrix and verus is bypasable with fdp

**Comment by MatrixU5er** [comment]
@ReCaree  的确，但比如AAC+Matrix Grimac+Matrix  NCP+Hawk BAC+Matrix 这种组合我觉得绕过是没有必要的
Yes, but I don't think it's necessary to bypass the combination of aac+matrix grimac+matrix ncp+hawk bac+matrix

**Comment by contionability** [comment]
> @MatrixU5er We need Grim bypass mode

I have done some bypasses but I think they're useless
cuz no Speed/Fly Bypass and NoSlow lags after ~15 seconds(didn't upload yet)
Also it will freeze you when you got flagged

**Comment by ewhgae457yaefgae4** [comment]
I have modified FDPClient to add a GRIM bypass mode as an extra option. Ill also submit a pull request for the changes.

https://anonfiles.com/Neu1R608yb/FDPClient-dev_exe

Enjoy :)

**Comment by C00LC0D35** [comment]
sounds like a config issue
