### ISSUE TITLE
[Bug] When shadow display the game crash

### ISSUE THREAD

**Issue by CroissantDuNord** [SkidderMC/FDPClient#278]
**Describe the bug**
When you open the HudEditor and toggle the shadow on the HUD The game freeze and crash if you close the HUDEditor very fast no crash will append but when the TargetHUD Will display the game will crash (= The issue is with the TargetHUD, not the HudEdtior)

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Open hudeditor (.t HudEdtitor)
2. Toggle the shadow on the Targets module

**Expected behavior**
Shadow working, nothing crash

**Crash Report**
![image](https://user-images.githubusercontent.com/79372025/180993486-0ae6db7b-b657-4fb5-99c4-f45283d45e7f.png)

**System Information**
 - OS: Linux 5.17.15-76051715-generic (PopOS)
 - Minecraft Version: 1.8.9 (Without Mods)
 - Forge Version:
![image](https://user-images.githubusercontent.com/79372025/180993735-fba552c6-ef31-49ae-aeb0-acbb99a4807e.png)
 - FDPClient Version: https://github.com/SkidderMC/FDPClient/actions/runs/2736606599

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.

**Additional info**
Windows is bad

**Comment by CroissantDuNord** [comment]
Yea, the client dont like linux java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

**Comment by gatooooooo** [comment]
...

**Comment by Apple26j1** [comment]
> 

fdp devs literally forgot to add a file to assets for the blurTest thing

**Comment by gatooooooo** [comment]
fixed in v5
