### ISSUE TITLE
[Bug] <FDP 4.4.5 Glitches Font,ClickGUI,HUDEditor,and ChestStealer Title.In PojavLauncher.>

### ISSUE THREAD

**Issue by ProSteve12301** [SkidderMC/FDPClient#282]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<When i edit Blur of Notification it removes every HUD and everything is Glitched..>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Open HUD Editor.
2. Edit an Elements Blur.
3. Select another Element.
4. Disappears.

**Expected behavior**
<When Died in PikaNetwork,Hud and Health bar are disappearing.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
`Sorry No ScreenShot cuz its lagging and exits.`

**Crash Report**
If your game crashed, please paste your crash report below.

```text
No Crash i report this for fixed.
```

**System Information**
 - OS: Android9(Oppo A12)
 - Minecraft Version: 1.8.9
 - Forge Version: Latest
 - FDPClient Version: 4.4.5

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine 1.8.9

**Additional info**
<Crashes when you turn off Optifine `Show GL Error: Off`(If you play Server or SinglePlayer{It delete config file and crash report are 0KB}).>

**Comment by ProSteve12301** [comment]
BTW Glitches Text

%ui.chest.stealing%
%ui.generate.offline%
%ui.alt.login%

**Comment by ProSteve12301** [comment]
Main Menu Glitch Text.
![Screenshot_2022-07-27-10-03-03-39_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/79408961/181145203-7796c26e-2b97-42d2-ac00-73db1780de64.jpg)

PikaNetwork HUD opened on ClickGUI.
![Screenshot_2022-07-27-10-06-47-73_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/79408961/181145298-21d365c9-cd17-4d1b-aba7-49ac418e5901.jpg)

HUDEditor.
![Screenshot_2022-07-27-10-07-00-78_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/79408961/181145382-6d9cfde1-0005-460b-97db-fbef497d5302.jpg)

BTW i used Bilalware Config but i manage it so i didn't expect to blame the config.

**Comment by ewhgae457yaefgae4** [comment]
Hi, I believe I have fixed the issues reported. Can you please test the development build to make sure and then ill make a github pull request.

https://anonfiles.com/X1scR00ey3/FDPClient-dev_exe

Thanks

**Comment by gatooooooo** [comment]
I belive this is fixed in latest

**Comment by CroissantDuNord** [comment]
Buy a computer
ez fix

**Comment by TheMosKau** [comment]
> Buy a computer
> ez fix

As the pojav launcher user, i wont going to buy a pc

**Comment by ProSteve12301** [comment]
> Buy a computer ez fix

Phone is cheaper than pc.You can play Minecraft Java on phone without buying PC(With Smooth FPS but glitchy).

**Comment by DinoFengz** [comment]
glitch text will be fix in latest version :)

**Comment by DinoFengz** [comment]
%ui.chest.stealing%
%ui.generate.offline%
%ui.alt.login%
