### ISSUE TITLE
[Request] ClientSpoofer

### ISSUE THREAD

**Issue by rafalohaki** [SkidderMC/FDPClient#285]
Add client spoof 
Lunar 
LabyMod
PvP Lounge

**Comment by Apple26j1** [comment]
Hello!
I remember Rise Client has a ClientSpoofer moudle. It can be found in their Rise 5.9 leak
I would have added this but unfortunately I do not know Kotlin. Sorry!

**Comment by NaNfps** [comment]
> Hello! I remember Rise Client has a ClientSpoofer module. It can be found in their Rise 5.9 leak I would have added this but unfortunately I do not know Kotlin. Sorry!

but u can use java

**Comment by gatooooooo** [comment]
I will look into it and add it to our staff suggestions.
