### ISSUE TITLE
FDPClient latest crashes during render ArmorStand when NoRender is on

### ISSUE THREAD

**Issue by FDPUser443** [SkidderMC/FDPClient#29]
[FDPCrashLogs.txt](https://github.com/SkidderMC/FDPClient/files/9077338/FDPCrashLogs.txt)

package net.ccbluex.liquidbounce.injection.forge.mixins.render;

public abstract class MixinRendererLivingEntity extends MixinRender {
...

if (noRender.getState() && noRender.shouldStopRender(entity)) {
            callbackInfo.cancel();       // it fails here :(
            return;
}

**Comment by DinoFengz** [comment]
wait dev to fix this bug
