### ISSUE TITLE
<GrimAC2.3.17 Fly bypass >Ohhhhhhhhhhhhhhhhhhh EZZZZZZZZZZ

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#292]
First, you need to stand on the square and set your scaffold tower mode to motiontp Then press jump to make your tower work, and it will rebound. There is an 80% to 90% chance of flying when scaffold is turned off in rebound
首先你需要站在方块上，把你的scaffold towermode 设置成 MotionTP.之后按跳跃使你的tower工作，它会回弹。在回弹中关闭scaffold有80%到90%的几率可以飞
It has been tested in person and is effective. Use grimac2.3.17 anti cheating
已经亲自测试有效,使用GrimAC2.3.17反作弊

https://user-images.githubusercontent.com/89892616/181865883-ec2b83ec-42d4-4839-add6-eb4cf33fd8c7.mp4

**Comment by MatrixU5er** [comment]
It is recommended that fdpclient add this flight

**Comment by C00LC0D35** [comment]
great it works hurray. now u use the macro system to use the motionTp "fly" and normall tower with another bind!
