### ISSUE TITLE
[Bug] <Title Here>

### ISSUE THREAD

**Issue by w111user** [SkidderMC/FDPClient#298]
Minecraft is crash when i launch FDPclient
![image](https://user-images.githubusercontent.com/109961811/182007715-47e31466-78bd-4fc1-afe2-18bc88473e26.png)

**Comment by DinoFengz** [comment]
e

**Comment by MatrixU5er** [comment]
@DinoFengz  Your build seems to be broken

**Comment by DinoFengz** [comment]
@MatrixU5er use latest version test

**Comment by DinoFengz** [comment]
it may works now

**Comment by MatrixU5er** [comment]
ok

**Comment by MatrixU5er** [comment]
yeah Good! it's working
