### ISSUE TITLE
<Title Here>holy is the hitbox code is even do anything? lmaooo

### ISSUE THREAD

**Issue by Zerolysimin** [SkidderMC/FDPClient#30]
"/*
 * FDPClient Hacked Client
 * A free open source mixin-based injection hacked client for Minecraft using Minecraft Forge by LiquidBounce.
 * https://github.com/SkidderMC/FDPClient/
 */
package net.ccbluex.liquidbounce.features.module.modules.combat

import net.ccbluex.liquidbounce.features.module.Module
import net.ccbluex.liquidbounce.features.module.ModuleCategory
import net.ccbluex.liquidbounce.features.module.ModuleInfo
import net.ccbluex.liquidbounce.value.FloatValue

@ModuleInfo(name = "HitBox", category = ModuleCategory.COMBAT)
class HitBox : Module() {
    val sizeValue = FloatValue("Size", 0.4F, 0F, 1F) "

**Comment by DinoFengz** [comment]
does u checked mixin?

**Comment by DinoFengz** [comment]
hitbox is using mixins . it just a module to ajust size of hitbox
