### ISSUE TITLE
[Bug] <Matrixnew speed> the speed can't working on Matrix6.8.19 (Move or BadPackets Flag) ping: 30ms

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#308]
![DF6@W(1}X$72V {$W}~9(F2](https://user-images.githubusercontent.com/89892616/182051477-735e2e13-eab0-4ceb-a97c-9925400ffd81.png)
For flag speed, I'm more used to vulcanhop
@DinoFengz

**Comment by DinoFengz** [comment]
no its for jartex / pika xDDDD

**Comment by DinoFengz** [comment]
latest not work i tested

**Comment by MatrixU5er** [comment]
ok
