### ISSUE TITLE
<Hypixel Zoom Fly bypass?> From BiliBili.com

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#312]
https://user-images.githubusercontent.com/89892616/182265965-7ad54832-ff0e-4b33-8a21-e56af1b80dfa.mp4

Replay: /replay bf53b0b2-2b27-49e5-b5a0-028512ef28b1 #9c787ca5          2022/7/28

**Comment by ReCaree** [comment]
stolen from noq
