### ISSUE TITLE
<Bypass> Add This Things To Fdp lol<Title Here>

### ISSUE THREAD

**Issue by Zerolysimin** [SkidderMC/FDPClient#313]
if (mc.thePlayer.onGround && Move.ismoving) {
                        if (mc.thePlayer.ticksExisted % 3 == 0) {
                        	MovementUtil.doStrafe(0.89);
                            mc.thePlayer.motionY = 0.38;
                            e.setY(0.38);
                        } else {
                            e.setX(0);
                            e.setZ(0);
                            mc.thePlayer.motionX = mc.thePlayer.motionZ = 0.0;                           
                        }
                    }

speed zonecraft

        	mc.timer.timerSpeed = 1F;
       		if(mc.thePlayer.onGround) {
       			mc.thePlayer.jump();
       			e.setY(0.42F);
       		}else {
       			mc.thePlayer.motionY = 0.0;
       			e.setY(0);
    			if(mc.thePlayer.ticksExisted % 20 < 10)
    				mc.timer.timerSpeed = 1.25f;
    			else
    				mc.timer.timerSpeed = 0.8f;
    			if(mc.thePlayer.ticksExisted % 20 == 9)
    				MovementUtil.doStrafe(MovementUtil.getSpeed()*1.125);
    			if(mc.thePlayer.ticksExisted % 20 == 1)
    				MovementUtil.doStrafe(0.2783*1.2);
    		}
    	}

fly zonecraft

**Comment by Zerolysimin** [comment]
code from my client

**Comment by MatrixU5er** [comment]
good @DinoFengz  @C00LC0D35

**Comment by DinoFengz** [comment]
i already code so wait for the releases!

**Comment by DinoFengz** [comment]
also matrix nofall will be added

**Comment by DinoFengz** [comment]
done
