### ISSUE TITLE
Cant Build

### ISSUE THREAD

**Issue by CMCat-Xicheng** [SkidderMC/FDPClient#322]
Access https://repo.getfdp.today/com/github/Kawa1Ares/Elixir/1.2.6/Elixir-1.2.6.pom denied
Cannot Find https://repo.gradle.org/ui/native/jcenter/net/minecraftforge/fernflower/2.0-SNAPSHOT/fernflower-2.0-SNAPSHOT.pom

**Comment by gatooooooo** [comment]
rip

**Comment by CMCat-Xicheng** [comment]
fuck gardlew i can build on github
