### ISSUE TITLE
issue building fdp with intelliJ

### ISSUE THREAD

**Issue by Celllnside** [SkidderMC/FDPClient#324]
im trying to build/debug fdp with intellij but i get this error when i try to. 

> Task :compileKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 4 executed, 2 up-to-date
e: C:\Users\Cell\FDPClient\src\main\java\net\ccbluex\liquidbounce\features\module\modules\misc\AntiVanish.kt: (18, 12): Unresolved reference: audio
e: C:\Users\Cell\FDPClient\src\main\java\net\ccbluex\liquidbounce\features\module\modules\misc\AntiVanish.kt: (40, 87): Unresolved reference: player

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

i also get this error
e: C:\Users\Cell\FDPClient\src\main\java\net\ccbluex\liquidbounce\features\module\modules\misc\AntiVanish.kt: (18, 12): Unresolved reference: audio
e: C:\Users\Cell\FDPClient\src\main\java\net\ccbluex\liquidbounce\features\module\modules\misc\AntiVanish.kt: (40, 87): Unresolved reference: player
![image](https://user-images.githubusercontent.com/71746732/183126511-24c318d8-8f10-4dff-afac-2127b99afef2.png)

**Comment by gatooooooo** [comment]
i have this issue too, its not only you.

**Comment by CMCat-Xicheng** [comment]
fork this fuckin client and build it in github

**Comment by Apple26j1** [comment]
don't use intellij ez
JK even gato has this issue and I also had it like months ago

**Comment by C00LC0D35** [comment]
its working 4 me rn

**Comment by gatooooooo** [comment]
we fixed it please try again, if it fails please make a new issue (note we updated the readme instructions)
