### ISSUE TITLE
<Matrix6.8.25Hop Bypass>It's Working on Matrix6.8.10 Matrix6.8.14 Matrix6.8.19 Matrix6.8.24 Matrix6.8.25 and more. NoFlag!!!!!

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#333]
![{T7XOS(E OC@OLAX6YW0TI9](https://user-images.githubusercontent.com/89892616/183786147-017c0d51-7aa6-4232-a1a2-48f9c7b0f744.png)
TestServer : matrix.test.siuank.xyz
AntiCheat : Matrix6.8.25
EZZZZZZZZZZZZZZZ

**Comment by Dizwi** [comment]
wow thx

**Comment by MatrixU5er** [comment]
XD

**Comment by Uzbej444** [comment]
Too slow
