### ISSUE TITLE
Need Pika-network Config ？ Configure web site ： Github.com/MatrixU5er/Configs

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#338]
https://github.com/MatrixU5er/Configs/blob/main/configs/PikaViolence.json
Most importantly, you need IQ

**Comment by RealPacket** [comment]
nice **AD**

**Comment by RealPacket** [comment]
> https://github.com/MatrixU5er/Configs/blob/main/configs/PikaViolence.json Most importantly, you need IQ

you know its not a "Website", its a "Repo" (otherwise, link us to your website that isn't github)

**Comment by OrdinaryHacker** [comment]
very good confing, unfortunatelly there is the bug where killaura has sometimes trouble hitting target while strafing or just moving around even whem crosshair is on target. There are 2 fixes for that:
1. enabling always hittable (flaggy af when used with matrix noslow)
2. using higher randomcenter values (will flag you when too close to target)
3. disabling strafe in killaura
I use vanilla noslow with aftertick autoblock and always hittable to fix that bug.
PS: I like that longjump

**Comment by MatrixU5er** [comment]
@OrdinaryHacker I will make changes to my Killara in the near future. Thank you for your support
