### ISSUE TITLE
NCP Disabler if u can

### ISSUE THREAD

**Issue by Ds1nk** [SkidderMC/FDPClient#358]
听说现在blocksmc换了反作弊，换成ncp了
以前verus的时候飘的挺爽，现在想回味一下
对了，有些功能的中文译名没填上

**Comment by XuanmiaomiaoX** [comment]
用啥fdpus啊？用fdpcn！

**Comment by laoshuikaixue** [comment]
去你*的用usfdp

**Comment by gatooooooo** [comment]
what?

**Comment by Ds1nk** [comment]
智齿FDPCN 拒绝乳化外纪！！！！！！

**Comment by Ds1nk** [comment]
gatooooooo No one asks you anything. Go develop your FDPClient (I use FDPCN anyway)

**Comment by C00LC0D35** [comment]
Ds1nk, all fdpcn is skid my bypasses, sit down
