### ISSUE TITLE
[Suggestion ]update to 1.18.2

### ISSUE THREAD

**Issue by procrafter820** [SkidderMC/FDPClient#370]
1.8.9 is old so it cant be used in vulcan survival servers

**Comment by evghenii12** [comment]
use this https://www.curseforge.com/minecraft/mc-mods/viaforge

**Comment by procrafter820** [comment]
> use this https://www.curseforge.com/minecraft/mc-mods/viaforge

viaforge neither adds offhand or remove right click block which doesn't work in 1.18...

**Comment by gatooooooo** [comment]
use a new client, we wont support new versions.
