### ISSUE TITLE
<Matrix6.x Speed >Can you write this custom speed as mode? It can bypass all versions of matrix6. I think everyone needs it

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#375]
![image](https://user-images.githubusercontent.com/89892616/186036374-7e73632f-c2f5-4c66-9e33-2b56206b238b.png)

**Comment by MatrixU5er** [comment]
YBoost : CustonAddYMotion = -0.116

**Comment by C00LC0D35** [comment]
this aint fast + 1 month ago
