### ISSUE TITLE
Pasted client

### ISSUE THREAD

**Issue by Cacti4** [SkidderMC/FDPClient#388]
just delete the repo

**Comment by evghenii12** [comment]
ok and they wanna make cheating community more open so they skid rise or any clients.

**Comment by Zerolysimin** [comment]
if fdp dont exist. then rip for 0$ client user....... since lime is discounected. and wont get any more bypass update, and lb++ is idk

**Comment by evghenii12** [comment]
Zerolysimin liquidbounce exists.

**Comment by Zerolysimin** [comment]
> Zerolysimin liquidbounce exists.
1 years no bypass update?

**Comment by evghenii12** [comment]
Scripts exists?

**Comment by Zerolysimin** [comment]
> Scripts exists?
okay. i give up.. my last answer is there still some people that doesnt know how to make script / make bypass in a script

**Comment by evghenii12** [comment]
ye i guess...

**Comment by gatooooooo** [comment]
wow such comedy! being that hilarious must be tiring
