### ISSUE TITLE
[Bug]ClickGUI mode white is buggy <Title Here>

### ISSUE THREAD

**Issue by procrafter820** [SkidderMC/FDPClient#397]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Make CLickGUI mods as white..then search any module on top..try enabling it...most time you need to click 7-10 times to enable it

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 
2. 
3. 
4. 

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: MacOS12
 - Minecraft Version: 1.8.9(or else what?)
 - Forge Version: latest
 - FDPClient Version: latest

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- viaforge latest
- optifine latest

**Additional info**
<Add any other context about the problem here.>

**Comment by alianik228** [comment]
opengl error 💀

**Comment by gatooooooo** [comment]
il have a look

**Comment by RealPacket** [comment]
yes the CLick GUI

**Comment by C00LC0D35** [comment]
bro what?

**Comment by C00LC0D35** [comment]
when the screenshots / video is empty mometno
