### ISSUE TITLE
Improve Fucker

### ISSUE THREAD

**Issue by ZhoJAVA** [SkidderMC/FDPClient#407]
Improve Fucker, for example Can't bypass BlockDrop, but Free Cam can bypass BlockDrop. Why is this?

**Comment by gatooooooo** [comment]
Jesus that is a funny title

**Comment by C00LC0D35** [comment]
becuz freecam litterally doesnt send any packets to the server or do anything that "cheaty", it litterally just moves the camera positon and doesnt tell the server about it
