### ISSUE TITLE
new target hud

### ISSUE THREAD

**Issue by rgd0409** [SkidderMC/FDPClient#416]
add rise targetHUD "otherother", becouse I think it can appeal to many people including me

**Comment by gatooooooo** [comment]
screenshot?

**Comment by rgd0409** [comment]
https://www.youtube.com/watch?v=XdoNmouMLAE 0:14

**Comment by procrafter820** [comment]
It'd be great

**Comment by EnderDrago0** [comment]
YES add

**Comment by C00LC0D35** [comment]
yez
