### ISSUE TITLE
[Bug] <autoblock not working properly >

### ISSUE THREAD

**Issue by Areunerdlol** [SkidderMC/FDPClient#417]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<if you enable killaura and hold your right click button it will autoblock but if you hold it for more than 4 sec and let go to stop autoblocking it would start to semi fake autoblock what i mean by that is that the block is not real it is fake but you still get slowed down like you are autoblocking for real even tho you don't have the right mouse button held>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. enable killaura
2. hold rightclick for more than 4 secs
3. let go of right click and you would still be "semi fake autoblocking" like i explained above
4. 

**Expected behavior**
<it should have stopped autoblock >

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
win 10
1.8.9
11.15.1.2318
latest version

**System Information**
 - OS: [e.g. Windows 10]   
 - Minecraft Version: [e.g. 1.8.9]   
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>
none
**Additional info**
<Add any other context about the problem here.>

**Comment by C00LC0D35** [comment]
dont do that then
