### ISSUE TITLE
[no proof] Virus Dectected (RAT)

### ISSUE THREAD

**Issue by JustAFreeGuy** [SkidderMC/FDPClient#419]
I checked through the code and did a deep virus scan, turns out there is a rat in the latest version of fdp (4.6.0), but till 4.5.5b there is no virus, why tho? did the GitHub get hacked or smth

**Comment by gatooooooo** [comment]
send proof of your allegations, don't spread rumours without proof,
please note: virustotal does not count and you may be bullied if you try to use it as proof.

**Comment by gatooooooo** [comment]
Closing due to lack of proof, please make another issue if you have a Security issue.
