### ISSUE TITLE
<Question>Fork Build Error

### ISSUE THREAD

**Issue by AllCheeks** [SkidderMC/FDPClient#48]
Run ./gradlew setupCiWorkspace && ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-[6](https://github.com/AllCheeks/FDPClient/runs/7365440908?check_suite_focus=true#step:5:7).9.1-all.zip
..............10%..............20%...............30%..............40%..............50%...............60%..............[7](https://github.com/AllCheeks/FDPClient/runs/7365440908?check_suite_focus=true#step:5:8)0%..............[8](https://github.com/AllCheeks/FDPClient/runs/7365440908?check_suite_focus=true#step:5:9)0%...............[9](https://github.com/AllCheeks/FDPClient/runs/7365440908?check_suite_focus=true#step:5:10)0%..............[10](https://github.com/AllCheeks/FDPClient/runs/7365440908?check_suite_focus=true#step:5:11)0%
Welcome to Gradle 6.9.1!
Here are the highlights of this release:
 - This is a small backport release.
 - Java 16 can be used to compile when used with Java toolchains
 - Dynamic versions can be used within plugin declarations
 - Native support for Apple Silicon processors
For more details see https://docs.gradle.org/6.9.1/release-notes.html
Starting a Gradle Daemon (subsequent builds will be faster)
FAILURE: Build failed with an exception.
* Where:
Build file '/home/runner/work/FDPClient/FDPClient/build.gradle' line: 6
* What went wrong:
Plugin [id: 'net.minecraftforge.gradle.forge', artifact: 'com.github.xcfrg:ForgeGradle:ddb1eb0'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.xcfrg:ForgeGradle:ddb1eb0')
  Searched in the following repositories:
    MavenRepo
    Gradle Central Plugin Repository
    maven(https://maven.minecraftforge.net/)
    maven2(https://jitpack.io/)
    maven3(https://repo.spongepowered.org/repository/maven-public/)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in [15](https://github.com/AllCheeks/FDPClient/runs/7365440908?check_suite_focus=true#step:5:16)s
Error: Process completed with exit code 1.

于是我把settings.gradle里的
Line13   useModule("com.github.xcfrg:ForgeGradle:${forgegradle_version}")
修改为其他库，构建成功了
Line13New	     useModule("com.github.Skytils:ForgeGradle:${forgegradle_version}")

**Comment by ReCaree** [comment]
![image](https://user-images.githubusercontent.com/86810014/179339004-dc0b2d6f-6576-4252-a7b8-f3bbb1ba25a1.png)
readddddddddddddddddddddddddd

**Comment by AllCheeks** [comment]
> ![图片](https://user-images.githubusercontent.com/86810014/179339004-dc0b2d6f-6576-4252-a7b8-f3bbb1ba25a1.png) readdddddddddddddddddddddddddddd

其实我是使用GITHUB ACTIONS :D 那么已经解决了
