### ISSUE TITLE
<FDPCN>Adout FDPCN(FDPClientChina)

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#489]
置顶发给新成员关于SkidderMC: 之前有一个外国人加入了UnlegitMC的团队并踢出了所有的原始dev，封锁了仓库并创建了SkidderMC。所以现在的SkidderMC是由外国人谋权篡位所建，其中没有任何一个中国人或是UnlegitMC原始开发人员。特此创建名为UnlegitMinecraft的github组织，并创建FDPCN Client(别名FDP+)Dev均为中国人，原汁原味。
我们的FDPCN拥有更高的帧率，更好的绕过，更美的UI，感谢大家的选择
并且SkidderMC辱华，我们也不能保证有没有远控在他们的版本中。
唯一Github:http://github.com/UnlegitMinecraft/FDPClientChina
官方网站: https://fdpclient.clu/b/
QQ群: 413868243
Puting sent to new members about SkidderMC: Before, a foreigner joined the team of UnlegitMC and kicked out all the original devs, blocked the warehouse and created SkidderMC. So the SkidderMC is now built by foreigners seeking power and usurping power. There is no Chinese or original developer of UnlegitMC. It is hereby to create a github organization named UnlegitMinecraft, and create FDPCN Client (alias FDP+) Dev, all of which are Chinese.

Our FDPCN has higher frame rate, better bypass, and more beautiful UI. Thank you for your choice

And SkidderMC insults China. We can't guarantee whether it is remotely controlled in their version.

Unique Github: http://github.com/UnlegitMinecraft/FDPClientChina

Official website: https://fdpclient.club/

QQ group: 413868243

Note: All resources are from China's social software Tencent QQ
Although I am a Chinese, I still believe in SkidderMC/FDPClient

**Comment by gatooooooo** [comment]
lmao

**Comment by PlayMcBKuwu** [comment]
> lmao

fdpCN dead in 2022/11
