### ISSUE TITLE
How about clarifying the code style rules?

### ISSUE THREAD

**Issue by hsheric0210** [SkidderMC/FDPClient#510]
As the code in this repository is currently not formatted well

[Coding conventions](https://kotlinlang.org/docs/coding-conventions.html)
[Kotlin style guide](https://developer.android.com/kotlin/style-guide)

**Comment by Mathrandom7910** [comment]
Alright guys, lets refactor the entire client so this one person can have a slightly better visual appeal to some of the code.

**Comment by Apple26j1** [comment]
> As the code in this repository is currently not formatted well
> 
> [Coding conventions](https://kotlinlang.org/docs/coding-conventions.html) [Kotlin style guide](https://developer.android.com/kotlin/style-guide)

Agreed, thinking of adding that to the README.md but then my pull request would maybe get closed and denied sadly

**Comment by C00LC0D35** [comment]
no ones gonna read that, if u wanna clean up the code, go ahead lol
