### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Exevity** [SkidderMC/FDPClient#512]
When i open fdp client the start screen is just plain black, i can still click the multiplayer,altmanager, etc.. i just cant see them is this normal?

**Comment by TheMosKau** [comment]
yeah its normal, we designed for everyone who is blind.

**Comment by ADevLogv** [comment]
Yes

**Comment by SofiaxFdp** [comment]
@TheMosKau I'm blind .

**Comment by Apple26j1** [comment]
> yeah its normal, we designed for everyone who is blind.

LOL

**Comment by gatooooooo** [comment]
turn off optifine fast renderer (its in optionsof.json)
