### ISSUE TITLE
Pojav Performance<Title Here>

### ISSUE THREAD

**Issue by Penaq** [SkidderMC/FDPClient#521]
5.0.0b is laggy asf on pojav sometimes it's hang please help.

**Comment by Apple26j1** [comment]
FDP Client was never made for mobile phones, also Pojav is not an official Minecraft Launcher + Minecraft is made for PCs not mobile phones

**Comment by gatooooooo** [comment]
we wont fix any pojav issue, if it crashes way may, but working is good enough for us.

**Comment by Penaq** [comment]
Oops my bad its not really lag its the config problem

**Comment by gatooooooo** [comment]
create a new issue if you experience anymore issues
please provide more info when you do
