### ISSUE TITLE
[Bug] Wrong cps calculations

### ISSUE THREAD

**Issue by OctantCoder** [SkidderMC/FDPClient#534]
**Describe the bug**
Killaura's/autoclicker's/otherModules,WhichUsesTimeUtils.randomClickDelay/ cps are incorrect (for example if min cps is 10 and max cps is 20 killaura's cps will never reach 20 (but it should), but it also with all other cps values). This is not only fdp problem, original lb and all other custom builds I saw have such problem

**System Information**
 - OS: [Linux mint (it also happens on all other OS]
 - Minecraft Version: [1.8.9]
 - FDPClient Version: [latest]

**Comment by AneryCoft** [comment]
if you set min20 max 20？

**Comment by IntaveCoreDev** [comment]
> if you set min20 max 20？

no, this bug makes you hit less, so from a range of possible cps it uses smaller one, so there is no difference between 10 to 30 and 10 to 40, but when min cps is 20 and max is same it works fine

**Comment by C00LC0D35** [comment]
imagine L

**Comment by C00LC0D35** [comment]
no, its just randomizes each delay between clicks to a value between the min cps average delay and the max cps average delay. and the cps counter shows basically the average of all the delays. if it gets to the min or max, that would be very statistically impossible, especially as u increase the cps. i dont see anything wrong with the code mathimatically. plus liquidbounce made it and liquidbounce is god

**Comment by qazwsx-11** [comment]
It's because click delay is randomised between the min and max cps, so it's unlikely for it to hit exactly 20 cps.

**Comment by IntaveCoreDev** [comment]
> no, its just randomizes each delay between clicks to a value between the min cps average delay and the max cps average delay. and the cps counter shows basically the average of all the delays. if it gets to the min or max, that would be very statistically impossible, especially as u increase the cps. i dont see anything wrong with the code mathimatically. plus liquidbounce made it and liquidbounce is god

yes, but I guess it isn't the way it should work. cause how can cps be max if it never reaches max value? I guess you can get a cps from min to max cps and just follow this cps
