### ISSUE TITLE
Add ground spoof for strafe

### ISSUE THREAD

**Issue by shittass** [SkidderMC/FDPClient#538]
bypass matrix

**Comment by TheMosKau** [comment]
no one cares

**Comment by MatrixU5er** [comment]
i think u can use GroundStrafehop to bypass

**Comment by qazwsx-11** [comment]
It would flag for ground spoof.

**Comment by shittass** [comment]
matrix will not detect ground spoof if the distance to the ground is less than 1

**Comment by C00LC0D35** [comment]
# matrix anticehat
