### ISSUE TITLE
[FEATURE] Use the new TargetHUD system from LiquidBouncePlus / LiquidBouncePlusPlus

### ISSUE THREAD

**Issue by gabrielvicenteYT** [SkidderMC/FDPClient#542]
This system allows you to create TargetHUDs with alot less effort. It will also allow SkidderMC and it's contributors to fix crashes easily, since each mode has it's own respective file.
The TargetHUD system in LiquidBouncePlusPlus CAN be converted to Kotlin, but it's better to just rewrite it entirely.

**Comment by gatooooooo** [comment]
we had this around the 4.45 era, it caused bugs
