### ISSUE TITLE
Add AutoGG module

### ISSUE THREAD

**Issue by SofiaxFdp** [SkidderMC/FDPClient#566]

**Comment by C00LC0D35** [comment]
ggs!

**Comment by SofiaxFdp** [comment]
Please add :(

**Comment by ImGGAAVVIINN** [comment]
yes add

**Comment by mallusrgreatv2** [comment]
just add the AutoGG mod, this is a forge mod, and its a hacked client for gods sake

**Comment by ImGGAAVVIINN** [comment]
It would be nice to have it built-in. It is a nice quality-of-life improvement

**Comment by MatrixU5er** [comment]
難道FDPClient的作弊性能能讓你使用AutoGG嗎? 請記住FDPClient是一個暴力客戶端而並非安全 如果需要安全 請前往Vape.gg
Does the cheating performance of FDPClient allow you to use AutoGG? Please remember that FDPClient is a violent client, not a security client. If you need security, please go to Vape.gg

**Comment by ImGGAAVVIINN** [comment]
> 

I am sorry, but I don't understand what you just say

**Comment by ImGGAAVVIINN** [comment]
> 難道FDPClient的作弊性能能讓你使用AutoGG嗎? 請記住FDPClient是一個暴力客戶端而並非安全 如果需要安全 請前往Vape.gg Does the cheating performance of FDPClient allow you to use AutoGG? Please remember that FDPClient is a violent client, not a security client. If you need security, please go to Vape.gg
I am sorry, but I don't understand what you just say

**Comment by gatooooooo** [comment]
> 難道FDPClient的作弊性能能讓你使用AutoGG嗎? 請記住FDPClient是一個暴力客戶端而並非安全 如果需要安全 請前往Vape.gg
> Does the cheating performance of FDPClient allow you to use AutoGG? Please remember that FDPClient is a violent client, not a security client. If you need security, please go to Vape.gg

lmao "violent", "security"

**Comment by KOFTWAR** [comment]
> > 難道FDPClient的作弊性能能讓你使用AutoGG嗎? 請記住FDPClient是一個暴力客戶端而並非安全 如果需要安全 請前往Vape.gg
> > Does the cheating performance of FDPClient allow you to use AutoGG? Please remember that FDPClient is a violent client, not a security client. If you need security, please go to Vape.gg
> 
> lmao "violent", "security"

Blatant Client and Ghost Client LOL

**Comment by qazwsx-11** [comment]
> 難道FDPClient的作弊性能能讓你使用AutoGG嗎? 請記住FDPClient是一個暴力客戶端而並非安全 如果需要安全 請前往Vape.gg
> Does the cheating performance of FDPClient allow you to use AutoGG? Please remember that FDPClient is a violent client, not a security client. If you need security, please go to Vape.gg

Truly
