### ISSUE TITLE
[Bug] something wrong while building

### ISSUE THREAD

**Issue by DcICU** [SkidderMC/FDPClient#573]
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16s
8 actionable tasks: 4 executed, 4 up-to-date

**Comment by C00LC0D35** [comment]
" see the compiler error output for details."
