### ISSUE TITLE
how to add [ key for a macro? it shows me "Unknown key to bind macro."

### ISSUE THREAD

**Issue by Flowing8175** [SkidderMC/FDPClient#574]
'=' key is 'equal'
'-' key is 'minus'
and what is [ key called? im not american so ye

**Comment by HelpingHands99** [comment]
[ is lbracket
] is rbracket

**Comment by C00LC0D35** [comment]
go to keybind manager, if u type out the macro where you serach for modules on a key and press enter, it will add the macro to that key
