### ISSUE TITLE
[Bug] Fucker raycast isuue

### ISSUE THREAD

**Issue by ghost** [SkidderMC/FDPClient#575]
Fucker doesn't raycast entites, so you will still break selected block even if there is an entity between you and target block (which prevents you from doing this in vanilla)

**Comment by Flowing8175** [comment]
can u tell me what is raycast? i jnow that exists but idk what it does

**Comment by IntaveCoreDev** [comment]
so it prevents you from hitting/breaking if there is something between you and target block/enemy. So issue is actually that fucker will still break a block, when there is an entity between you and target block

**Comment by gatooooooo** [comment]
funny name
