### ISSUE TITLE
[Main Menu} Main menu is completely black

### ISSUE THREAD

**Issue by scattyypie** [SkidderMC/FDPClient#581]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Main menu is completely black

**To Reproduce**
Old versions of fdp were working fine but when i downloaded fdp client 5.0 the main menu was completely black and i could still click somewhere on the screen and open stuff like settings

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**System Information**
 - Windows 10
 - Forge 1.8.9
 - Downloaded from tlauncher probably latest
 - FDPClient Version:5.0.0b (Main

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine

**Comment by C00LC0D35** [comment]
turn off fast render from vanilla mc and relaunch fdp
