### ISSUE TITLE
Multiple Things. (To change or add)

### ISSUE THREAD

**Issue by BackupVPR** [SkidderMC/FDPClient#582]
01# **Watermark** will be customizable. Like **colors, font, size (scale), animations. changable name.**
02# **Music player** like **Jello for Sigma 5.0**
03# **New clickgui's**. Like **Tenacity 5, Jello for Sigma 5.0, Rise 5.100**
04# The **watermark** is bugging with **Keystrokes**.
05# **Custom backgrounds, watermarks.**
06# Fix **JumpCircles** not showing.
07# **AutoGG and customizable KillInsults BUT users can be change the messages.**
08# Add **AntiCrash** for servers like **HyCraft**.
09# **Configs** will be listed on **clickgui** and we can **load/delete/rename/recolor (like Vape V4)**
10# **Fucker (BedBreaker) raycast** is **NOT breaking bed throught blocks**.
11# **Tenacity 5.0 themes/choices to hud elements.**
12# Fix **Stealer/InvManager's 0 delay crash bug.**
13# Fix **wrong cps calculations.**
14# Add **NoSpeed** to **KillAura and InfAura for less AntiCheat flags (for some anticheats).**
--Made by **@GameVPR**'s backup account **@BackupVPR**--

**Comment by C00LC0D35** [comment]
01# Watermark will be customizable. Like colors, font, size (scale), animations. changable name.
02# Music player like Jello for Sigma 5.0
03# New clickgui's. Like Tenacity 5, Jello for Sigma 5.0, Rise 5.100
04# The watermark is bugging with Keystrokes.
05# Custom backgrounds, watermarks.
06# Fix JumpCircles not showing.
07# AutoGG and customizable KillInsults BUT users can be change the messages.
08# Add AntiCrash for servers like HyCraft.
09# Configs will be listed on clickgui and we can load/delete/rename/recolor (like Vape V4)
10# Fucker (BedBreaker) raycast is NOT breaking bed throught blocks.
11# Tenacity 5.0 themes/choices to hud elements.
12# Fix Stealer/InvManager's 0 delay crash bug.
13# Fix wrong cps calculations.
14# Add NoSpeed to KillAura and InfAura for less AntiCheat flags (for some anticheats).
--Made by @GameVPR's backup account @BackupVPR--

1 no
2 no. use spotify, no point in increasing the jar size
3 they exist
4 will try to fix
5 u can change that ur self in hud designer and change the userbg.png image in fdp folder
6 will
7 change insult.json in fdp folder
8 use hycraft disabler (all it does is prevent crash)
9 yes wil come in 5.1.0
10 config issue, use around
11 make a hud urself, or go to #public-themes in the discord
12 no u
13 its correct
14 what?

**Comment by BackupVPR** [comment]
14: Add one thing to killaura named "NoSpeed",
killaura automaticly stop working with speed.

**Comment by C00LC0D35** [comment]
bro what? config issue. no one will fucking use that lool
