### ISSUE TITLE
[Bug] Flag fly crash

### ISSUE THREAD

**Issue by OctantCoder** [SkidderMC/FDPClient#585]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
When you enable fly flag mode and try exiting from game minecraft stops working (SINGLEPLAYER)
https://youtu.be/89PavuLJLwI

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. .fly mode flag
2. .t fly
3. Fly a bit
4. Exit from the SinglePlayer

**Comment by DinoFengz** [comment]
ok
