### ISSUE TITLE
[Bug] FDPClient crashes

### ISSUE THREAD

**Issue by cjh175** [SkidderMC/FDPClient#590]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
<A clear and concise description of what the bug is.>

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. start fdp
2. crash!

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
<img width="879" alt="image" src="https://user-images.githubusercontent.com/69102594/200093295-509802cf-edc6-4fe2-a8f1-205839e03847.png">

**Crash Report**
If your game crashed, please paste your crash report below.
[minecraft.log](https://github.com/SkidderMC/FDPClient/files/9942614/minecraft.log)
[latest.log](https://github.com/SkidderMC/FDPClient/files/9942615/latest.log)
```text
Crash after update Java

**System Information**
 - OS:Windows 11
 - Minecraft Version: 1.8.9
 - Forge Version:11.15.1.2318
 - FDPClient Version: 5.0.0
Java Version: 1.8.0_351, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- OptiFine_1.8.9_HD_U_H8.jar

**Additional info**
<Add any other context about the problem here.>
Crash after update Java

**Comment by C00LC0D35** [comment]
use an actual launcher

**Comment by cjh175** [comment]
it's my config issues, i delete all of my config and launched successfully
