### ISSUE TITLE
<About Buzz AntiCheat>I think we need some bypass about it，For example, copy and paste the Rise code。

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#594]
The FDP has not been updated for some time. It's time to copy it

**Comment by gatooooooo** [comment]
lmao you try it

**Comment by MatrixU5er** [comment]
Im noob .........................

**Comment by NerdHaxx** [comment]
https://www.youtube.com/watch?v=IRuJK3xrhp8 "inspiration" ;)

**Comment by MatrixU5er** [comment]
it is on rise6.0 but fdp not
