### ISSUE TITLE
Somethings

### ISSUE THREAD

**Issue by GameVPR** [SkidderMC/FDPClient#599]
[ADD] Text can glow and can be change the glow color.
[ADD] Rise 5.100 and Tenacity 5.0 clickgui.
[ADD] New disablers for anticheats like Verus, Vulcan, NCP, Matrix.
[ADD] Add config list in clickgui. (Like Vape V4)
[ADD] Support newer or older configs.
[F.I.X.] Fix the 0 delay crash bug or make minimum delay minimum is 1.
[F.I.X.] Fix JumpCircles
[F.I.X.] Update old disablers or make new disablers.

**Comment by gatooooooo** [comment]
> Tenacity 5.0 clickgui.

did you not update fdp to beta builds?
https://fdpinfo.github.io/download

**Comment by MatrixU5er** [comment]
I don't think Vulcan and Matrix need a Disabler because FDP can perfectly bypass all the functions except fly in Matrix anti cheating. I don't need to say more about Vulcan's bypass

**Comment by C00LC0D35** [comment]
brody really thought fix was an acronym

**Comment by scattyypie** [comment]
well vulcan patched the fly soo

**Comment by scattyypie** [comment]
and vulcan speed makes it so u dont take any kb and it flags velocity on vulcan

**Comment by MatrixAura** [comment]
1.Skid tenacity
2.Skid tenacity & Rise 5.100
3.Vulcan and Matrix don't need a Disabler
4.Easy
7. #617

**Comment by MatrixAura** [comment]
> [ADD] Text can glow and can be change the glow color. [ADD] Rise 5.100 and Tenacity 5.0 clickgui. [ADD] New disablers for anticheats like Verus, Vulcan, NCP, Matrix. [ADD] Add config list in clickgui. (Like Vape V4) [ADD] Support newer or older configs. [F.I.X.] Fix the 0 delay crash bug or make minimum delay minimum is 1. [F.I.X.] Fix JumpCircles [F.I.X.] Update old disablers or make new disablers.

1.Skid tenacity
2.Skid tenacity & Rise 5.100
3.Vulcan and Matrix don't need a Disabler
4.Easy
7.#617

**Comment by MatrixAura** [comment]
> [F.I.X.] Fix JumpCircles

Oh, I fixed it on #627
