### ISSUE TITLE
HackerDetector

### ISSUE THREAD

**Issue by llUnknownl** [SkidderMC/FDPClient#602]
I think jigsaw's hacker detector is better, FDPclient says everyone is using fly and speed. And jigsaw's dev released it's source code, maybe you can add that detector to FDP

Edit: I saw the detector's source code and it seems to be usin jigsaw's detector, so forget what I said XD. Btw the movements detector is a bit accurate, detects almost everyone using fly and speed.

**Comment by DinoFengz** [comment]
hnm

**Comment by NCPUser** [comment]
ok :fox_face:

**Comment by DinoFengz** [comment]
@gatooooooo https://github.com/PaceCodes/Jigsaw/tree/Jigsaw/Jigsaw%200.26/Jigsaw%200.26%20(1.8.8)/me/robbanrobbin/jigsaw/hackerdetect

**Comment by MatrixAura** [comment]
useless module

**Comment by opZywl** [comment]
> useless module

yes
