### ISSUE TITLE
Please add Off Ground in the Fucker module to Bypass Matrix Anticheat

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#608]

**Comment by MatrixAura** [comment]
是在挖床时修改onGround为false吗

**Comment by gatooooooo** [comment]
i am not understanding

**Comment by MatrixU5er** [comment]
在挖床时让反作弊认为你不在地面上 比如你在空中使用Freeze + Fucker 即可绕过
Let anti cheating think you are not on the ground when digging the bed. For example, you can bypass by using Freeze+Fucker in the air

**Comment by MatrixAura** [comment]
@MatrixU5er 请问把freeze和fucker绑定在一个按键上可以绕吗

**Comment by MatrixU5er** [comment]
@MartrixAura 可以是可以但是要手动跳远浮空

**Comment by C00LC0D35** [comment]
scripts
