### ISSUE TITLE
[Bug] 中文显示不正常

### ISSUE THREAD

**Issue by MatrixAura** [SkidderMC/FDPClient#610]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
中文字符挤在一起

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 在游戏里按下esc
2. 进入语言设置
3. 切换到中文
4. 发现中文字符挤在一起

**Expected behavior**
中文字符不会挤在一起

**Screenshots/Video**
[Screenshot](https://img1.imgtp.com/2022/11/19/HiESG1u1.png)

```text
Sorry, I don't understand English, so I use Chinese in this issue.
```

**System Information**
 - OS: [Windows 11]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [5.1.0(Main)]

**Comment by afdera** [comment]
字体问题

**Comment by MatrixU5er** [comment]
全是中国人是吧

**Comment by Li-Zi-stu** [comment]
这个问题一直都有，没修复的话尝试切换到英文（总比以前全是%XXXX%好一些）

**Comment by DinoFengz** [comment]
learn english haha
