### ISSUE TITLE
JumpCircle

### ISSUE THREAD

**Issue by MatrixAura** [SkidderMC/FDPClient#617]
Please skid jumpcircle from 

1. https://github.com/RandomForks/novoline/blob/main/src/cc/novoline/modules/visual/JumpCircle.java
2. https://github.com/jabask3dd3r/DestroySquad-src-leak/blob/main/client/feature/impl/visual/JumpCircle.java

**Comment by MatrixAura** [comment]
1. https://github.com/serbioZ/Rockstar-Client-src-deobf/blob/main/smirnov/ru/rockstar/client/features/impl/visuals/JumpCircle.java
2. https://github.com/LocalChineseMan/MythClient/blob/main/notthatuwu/xyz/mythrecode/modules/visuals/JumpCircle.java

**Comment by MatrixU5er** [comment]
This may take a long time because: 1. The clients are different 2. The file names are different

**Comment by MatrixAura** [comment]
我已经等不及了，快点端上来罢（急切）

**Comment by MatrixU5er** [comment]
主播也是寶貝啊,主播不會啊 太繞了 主播還要上網課

**Comment by MatrixAura** [comment]
skidding...

**Comment by MatrixAura** [comment]
主播也是仙贝（幻世）

**Comment by MatrixAura** [comment]
> 主播也是寶貝啊,主播不會啊 太繞了 主播還要上網課

主播也是仙贝（幻视）

**Comment by MatrixU5er** [comment]
你在B站关注了主播吗

**Comment by MatrixAura** [comment]
关注主播了
