### ISSUE TITLE
I think it's time to strengthen FDPClient 

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#625]
The bypass that FDP now has may no longer meet the needs of users, Karhu, Buzz, GrimAC FDP users may not be able to defeat some normal users due to some strong anticheat
FDP现在拥有的绕过可能不再满足用户的需求,Karhu,Buzz,GrimAC等一些较强的反作弊使FDP用户可能连一些正常用户都无法战胜

**Comment by MatrixAura** [comment]
I think it's time to strengthen Scripts

**Comment by MatrixAura** [comment]
鸡燃FDP无法实现一个一个有效的旁路，那么，Legit时代，来临罢（喜

**Comment by shittass** [comment]
什么时候fdp进入全面legit时代

**Comment by OrdinaryHacker** [comment]
You wont be able to bypass buzz on jartex/pika because of its broken raycast

**Comment by StarsHackerMC** [comment]
你需要知道的是比fdp好的客户端多了 坚持用绕不过的 什么思路

**Comment by contionability** [comment]
需要知道的是在8月份之前有一大半的Bypass都是我贡献的
我潜水了他们基本只能skid，能不能绕过懂的都懂（笑）

**Comment by DinoFengz** [comment]
💀

**Comment by DinoFengz** [comment]
open source project for dev is too bad. When the dev make a working bypass , anticheat dev can patched it easily cuz its open src. That's why fdp become bad
