### ISSUE TITLE
[Bug] killaura不打人

### ISSUE THREAD

**Issue by shittass** [SkidderMC/FDPClient#626]
在有些服务器killaura打人，有些服务器不打，而且antibot都关了，target全选了，反作弊全关闭都不打人
 - OS: [Windows 11]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [latest]
 
 Installed viaforge
 i can use English but I want to use Chinese

**Comment by NerdHaxx** [comment]
fdp dying :( no "quality" commits to repo nowadays

**Comment by MatrixU5er** [comment]
你是指Hmxix? 这确实有点问题

**Comment by shittass** [comment]
这个bug太几把脑残了

**Comment by DinoFengz** [comment]
check which modules that can remove aura target like teams

**Comment by KOFTWAR** [comment]
在一些服务器里确实不会打人，这不仅在SkidderFDP，在FDPCN同样也不会攻击玩家，这可能是代码的问题
