### ISSUE TITLE
[Bug] Please fix novoline clickgui

### ISSUE THREAD

**Issue by MatrixAura** [SkidderMC/FDPClient#628]
FDP Version: dev
In the Kill Aura, novoline clickgui.
the "range" exists, but the button itself doesn't.
I think it's onChanged's bug.
sorry for my s**t english.

**Comment by DinoFengz** [comment]
which build ?

**Comment by MatrixAura** [comment]
> which build ?

build e2cbf14

**Comment by MatrixAura** [comment]
> which build ?

5.1.0 Latest

**Comment by DinoFengz** [comment]
fixed
