### ISSUE TITLE
打开直接崩

### ISSUE THREAD

**Issue by chinabestcountry** [SkidderMC/FDPClient#637]
用的hmcl，所有与pcl有关的文件均已删除，但是窗口会跳出来提示fdp加载，日志如下:
[minecraft-exported-logs-2022-11-25T17-28-35.log](https://github.com/SkidderMC/FDPClient/files/10090354/minecraft-exported-logs-2022-11-25T17-28-35.log)
请帮帮我！
:)

**Comment by rsgikun** [comment]
fdp有时候会把部分进程认为pcl（猜测）

**Comment by rsgikun** [comment]
看看有没有mod冲突，新版本fdp我记得检测到pcl有弹窗的

**Comment by rsgikun** [comment]
看了日志，似乎是字体或者披风的问题

**Comment by rsgikun** [comment]
别开更好的字体

**Comment by DinoFengz** [comment]
Ok, its config bug.Maybe you didnot stop FDPClient when shutdown window.
You can try to find the file that is bugged like 
```
\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000
```
in FDPCLIENT-1.8 folder and delete it.

**Comment by chinabestcountry** [comment]
我将系统字体恢复了初始设置，在 FDPCLIENT-1.8 folder里没有找到任何不正常的文件，themes下是空的，font下有font.json和regular.ttf两个文件,但仍然崩溃
:)

**Comment by chinabestcountry** [comment]
附上hmcl的报告
![1669378497421](https://user-images.githubusercontent.com/94364764/203984006-8739319e-7f3d-404e-b625-7667ed776cc4.png)

**Comment by chinabestcountry** [comment]
我在另一个地方创建游戏成功运行

**Comment by MatrixAura** [comment]
删除capes.json

**Comment by gatooooooo** [comment]
inactive issue
