### ISSUE TITLE
[request] can u add colormixer like in liquidbounce+/liquidbounce++

### ISSUE THREAD

**Issue by f4r2** [SkidderMC/FDPClient#642]
idk

**Comment by C00LC0D35** [comment]
what does colormixer even do?

**Comment by evghenii12** [comment]
@C00LC0D35 mixes colors like this https://streamable.com/nllfmt

**Comment by f4r2** [comment]
@gatooooooo so will u add it? its been months

**Comment by MatrixAura** [comment]
Useless

**Comment by gatooooooo** [comment]
> @gatooooooo so will u add it? its been months

shit i forgot about it



> Useless

it is a rainbow util so its cool

**Comment by opZywl** [comment]
shit
