### ISSUE TITLE
[Bug] <不显示图标 no icon with play game>

### ISSUE THREAD

**Issue by 8-python-snhk** [SkidderMC/FDPClient#652]
好家伙 打开游戏 任务栏直接不显示图标（就是windows那个图标）
![image](https://user-images.githubusercontent.com/69177759/205470863-7efed7ca-adcb-4cd9-aa2c-130999ccea73.png)

**Comment by afdera** [comment]
6

**Comment by DinoFengz** [comment]
Will fix in future

**Comment by DinoFengz** [comment]
Fixed by dino 👍
