### ISSUE TITLE
Killaura-strafe movement problem

### ISSUE THREAD

**Issue by hanjia01** [SkidderMC/FDPClient#653]
Only turn on killaura and jump to the left (or right) front with sprint, without any Combat
it is detected by anti-cheat. sometimes maybe lagg by anticheat
But when Killaura-strafe selected "Off" this problem will not occur.

**Comment by MatrixU5er** [comment]
有些反作弊的确能强 比如:Grim 在您说的这种情况会回弹 我认为它只是Aim 检测 因为当你打开BowAimbot的时候有一样的检测

**Comment by hanjia01** [comment]
但是在原版LB或一些老版本的FDP不会有上述情况
我认为这不应该是Aim检测 因为只启用了Killaura 并没有瞄准任何目标

**Comment by Davidisnotavailable** [comment]
they should add jumpfix to fix it

**Comment by Davidisnotavailable** [comment]
"strafe" in killaura is movement fix it makes your movement for legit

**Comment by rsgikun** [comment]
> 那个Strafe的问题和TargetStrafe有点关系 但是最近的一些更新又多了新问题，导致现在基本修不动（那一坨代码看着都费劲得很）
开启targetstrafe你关掉杀戮就会自带strafe,shitcode,着色器也全是问题，鸽鸽你要不从0开始写吧，base liquidbounce++

**Comment by contionability** [comment]
Fixed

**Comment by MatrixAura** [comment]
@opZywl close it

**Comment by MatrixAura** [comment]
@contionability 关闭这个issue
