### ISSUE TITLE
Todo: Rewrite Killaura 重写杀戮以及相关Utils

### ISSUE THREAD

**Issue by contionability** [SkidderMC/FDPClient#657]
wait me until January :)

**Comment by contionability** [comment]
TODO List:
Seperate Visuals from Killaura (sub-modules, like flys and criticals)
Rewrite the bullshit construct

**Comment by contionability** [comment]
妈的顺便还有那个脑残的Antibot Filter
会让Raycast坏掉（BetterAC：6）

**Comment by gatooooooo** [comment]
nice to see you back cont, join the discord

**Comment by shittass** [comment]
我觉得这杀戮回滚都比现在好
真的很烦人这个杀戮
调得头发都掉光了也绕不了很多反作弊

**Comment by contionability** [comment]
重写得了
本来一开始继承过来的旧架构就不是很合理
谁会把Rotation Update放在Motion Event啊，这东西一定是放在Update Event或者Strafe Event才合理的
我的评价是逻辑混乱，不如推倒重写

**Comment by OrdinaryHacker** [comment]
Hope they will fix Raycast issue. Its in FDP since 4.0
