### ISSUE TITLE
希望在未来添加的功能

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#667]
[+]Killaura Strafe 添加更多的Strafe选项以绕过更多反作弊
[+]Matrix Step/Spider 让Matrix6.9.2Tower 在墙上进行工作
[+]Buzz Flight 像飞行大端Rise一样的Flight 希望能Skid
[+]Hypixel(WatchDog) Flight 在众多视频网站(BiliBili YoutuBe) 上都有绕过视频 比如:WatchDog Packet Flight 
[+]Disabler Custom 让禁用器能够自定义发包(Packets) 或许我们能从中发现新的绕过
[=]Scaffold 希望修复这个脑残代码 它永远将不再绕过像GrimAC这样的反作弊 
[=]自FDPClient v5.1.5 以来我的FDPClient 在窗口上失去了原有的“F”图标 变为了默认的.exe 图标
[ ! ] 最好不要删除任何旧的Mode 因为我们不知道它能否有一天会绕过一个新的反作弊

**Comment by 8-python-snhk** [comment]
支持

**Comment by Li-Zi-stu** [comment]
插一嘴：
[ ! ] 重写Killaura的Strafe，如果可以Raycast也重写

**Comment by DinoFengz** [comment]
Disabler Custom :
You can use script with packet event listener to get / modify / cancel packet :+1:

**Comment by rikoshet185** [comment]
> 

I don't think it's a good idea to keep the old modes. AACBHops and NCP speed strongly clog gui. Some bypasses don't work properly (like Packet Tower). It is better to find some alternative way (For example, the ability to unload old crawls for those anti-cheats that are on 1% of servers)

**Comment by C00LC0D35** [comment]
Wdym new strafe modes, what other modes r there fam?
Just use colide tower
to make a custom disabler make a script lol
scaffold just get a better config
