### ISSUE TITLE
[Bug] Skid (this is not a joke)

### ISSUE THREAD

**Issue by CheatMaker** [SkidderMC/FDPClient#668]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
This client has skidded code

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. open code
2. die of cringe
3. 
4. 

**Expected behavior**
Half decent non skidded code

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**How 2Fix**
Delete this repo

```text
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Example Mod 1.0>

**Additional info**
<Add any other context about the problem here.>

**Comment by GlitchedPanda** [comment]
Nice

**Comment by CheatMaker** [comment]
fr bruh

**Comment by gatooooooo** [comment]
no.

**Comment by ErGiova** [comment]
no.

**Comment by Liam5750** [comment]
no.

**Comment by CheatMaker** [comment]
yes

**Comment by Liam5750** [comment]
yes
