### ISSUE TITLE
We need FDPClient to add more bypass about Karhu

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#681]

**Comment by NaNfps** [comment]
bypass and create it by urself

**Comment by NaNfps** [comment]
bypass it by urself xd

**Comment by MatrixAura** [comment]
尝试使用
![image](https://user-images.githubusercontent.com/110614702/221407089-6ea1503e-693b-47a1-bdb5-76a56c2946c9.png)
来编写一个

**Comment by K0itoyuu** [comment]
We need VeibaeClient to add more bypass about Karhu,GrimAC,TakaAC,AAC,Matrix,Spartan,Medusa,Verus,Vulcan,Horizon,ACR,Kauri
