### ISSUE TITLE
Intave/ZQAT寰宇中国(Neko) Noslow 

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#685]
https://github.com/RE-KevinClient/KevinClient-Reborn/blob/master/src/minecraft/kevin/module/modules/movement/NoSlow.kt

**Comment by MatrixU5er** [comment]
i think i can get it

**Comment by contionability** [comment]
确定这个不是Fake NoSlow？
一直Release

**Comment by siuank** [comment]
> 

抄Rise的

**Comment by siuank** [comment]
我抄Rise的（
