### ISSUE TITLE
[Bug] Issue: Bug report

### ISSUE THREAD

**Issue by TheMosKau** [SkidderMC/FDPClient#687]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
A clear and concise description of what the bug is

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 1.
2. 2.
3. 3.
4. 4.

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.

**Crash Report**
If your game crashed, please paste your crash report below.

```text
Paste Here
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [e.g. 2.0-PRE2]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Example Mod 1.0

**Additional info**

**Comment by timof121** [comment]
same here, getting this issue

**Comment by SnooComics9452** [comment]
same, this issue makes the client unplayable

**Comment by Nerbles1** [comment]
i thought i was the only one with this issue, thanks for reporting it

**Comment by C00LC0D35** [comment]
Proof lb++ is better client LOL

**Comment by TheMosKau** [comment]
> Proof lb++ is better client LOL

![20221218_175052](https://user-images.githubusercontent.com/77763580/217203366-3fbe5485-18eb-4cfa-8ff5-8db560d946a9.jpg)
