### ISSUE TITLE
Jump but motion is wrong

### ISSUE THREAD

**Issue by siuank** [SkidderMC/FDPClient#697]
in Criticals - MotionCriticals - jump
```kotlin
"jump" -> mc.thePlayer.motionY = 0.42
```

but it can be detected by the following code in the server:
```java
double motionY = moveEvent.getTo.getY() - moveEvent.getFrom().getY();
double different = motionY - 0.42;
if (Math.abs(different) < 1.7E-14) {
    fail("Jump with wrong motion");
}
```
because the correct motion should be 0.42F (float instead of double)
but the best way is `mc.thePlayer.jump()`, instead of `mc.thePlayer.motionY() = 0.42f.toDouble()`

**Comment by siuank** [comment]
the same problems in many modules, such as Speed Velocity and so on

**Comment by NerdHaxx** [comment]
Best Client BIG W!

**Comment by NerdHaxx** [comment]
also i completely agree making the player jump instead of just changing motionY (for a jump) is far better

**Comment by rsgikun** [comment]
正确的，不理解fdp为什么不直接jump还要motionY如果有jumpboost直接去世并且vulcan好像能检测

**Comment by siuank** [comment]
> 正确的，不理解fdp为什么不直接jump还要motionY如果有jumpboost直接去世并且vulcan好像能检测

算是LiquidBounce的问题吧
FDP直接用下来就没动过了

**Comment by MatrixAura** [comment]
It's fixed on JumpVelocity

**Comment by rsgikun** [comment]
> It's fixed on JumpVelocity

fdp不是早修复了吗，现在有jump和Motion
