### ISSUE TITLE
[ADDITION] RotationStrafe

### ISSUE THREAD

**Issue by gabrielvicenteYT** [SkidderMC/FDPClient#705]
**Additions**
`[+] Add RotationStrafe to Scaffold`

### Why I want this added
This would allow people to bypass Grim anticheat, because it would make the movements "legit"

**Comment by contionability** [comment]
I'll add it in a few days

**Comment by OrdinaryHacker** [comment]
also for fucker.

**Comment by rsgikun** [comment]
> 也适合混蛋。
任何带有silentrotation的都适合

**Comment by contionability** [comment]
Updated
Closed
