### ISSUE TITLE
[Bug] <Pojavlauncher Crash Still Exist?!>

### ISSUE THREAD

**Issue by ProSteveBedrock** [SkidderMC/FDPClient#710]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Crash when launching(on loading mods)

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1.Install FDP Simple

**Expected behavior**
<A clear and concise description of what you expected to happen.>

**Screenshots/Video**

**Crash Report**
If your game crashed, please paste your crash report below.
[crash-2023-02-19_22.53.12-client.txt](https://github.com/SkidderMC/FDPClient/files/10782012/crash-2023-02-19_22.53.12-client.txt)
[log-2023-02-19_22.53.12-client.txt](https://github.com/SkidderMC/FDPClient/files/10782018/log-2023-02-19_22.53.12-client.txt)

**System Information**
 - OS: [Android 10]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318(Latest)]
 - FDPClient Version: [Latesy Beta]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- <Optifine 1.8.9>

**Comment by ProSteveBedrock** [comment]
https://user-images.githubusercontent.com/123849671/220052479-c34ec2c1-c91e-4090-8d56-b399ff6a8206.mp4

LoL the video was compressed to uploaded.

**Comment by NerdHaxx** [comment]
get a pc smh. that java emulator for android has many problems with mods

**Comment by ProSteveBedrock** [comment]
Please Fix im still on FDP5.0.0b.
Other Liquidbounce fork also have the same crash(Liquidbounce+,Liquidbounce++,Nighty X).

**Comment by cheesethesylveon** [comment]
filipino moment

**Comment by Davidisnotavailable** [comment]
no one cares about pojavlauncher

**Comment by ProSteveBedrock** [comment]
Happy Anniversary Bug!!!🎉🎊🎉🎊
Its 1 year since this bug happen and no updates at all?
FDP Dev why?
Im part of cheating community and the FDP 5.0.0b modules has been patched and i can't try the new bypasses and features.
Please Fix🔧🔧🔧.

**Comment by NerdHaxx** [comment]
> Happy Anniversary Bug!!!🎉🎊🎉🎊 Its 1 year since this bug happen and no updates at all? FDP Dev why? Im part of cheating community and the FDP 5.0.0b modules has been patched and i can't try the new bypasses and features. Please Fix🔧🔧🔧.

nah too much work. first we'll have to trace the bug, then try to fix it and get it to somehow work with java emulator & still it could easily break fdp for other platforms or it'll start crashing again if your emulator gets some *Big* update that changes critical stuff. So for now I'm pretty sure no one's gonna look into this as it is kinda hard to fix (coz its the emulator's problem not fdp's) and probably not worth the waste of time coz it may not work at all

**Comment by NerdHaxx** [comment]
@ProSteveBedrock you can try removing optifine from mods folder idk if its gonna prevent fdp from crashing but u can try :)

**Comment by ProSteveBedrock** [comment]
> @ProSteveBedrock you can try removing optifine from mods folder idk if its gonna prevent fdp from crashing but u can try :)

Sadly not work either,i think this is connected to the fdp mixin.

**Comment by contionability** [comment]
> > @ProSteveBedrock you can try removing optifine from mods folder idk if its gonna prevent fdp from crashing but u can try :)
> 
> Sadly not work either,i think this is connected to the fdp mixin.

may fixed, test it again

**Comment by contionability** [comment]
upload the crash log if it doesn't work

**Comment by ProSteveBedrock** [comment]
Here
[log-2023-02-26_16.07.51-client.txt](https://github.com/SkidderMC/FDPClient/files/10833245/log-2023-02-26_16.07.51-client.txt)
[crash-2023-02-26_16.07.51-client.txt](https://github.com/SkidderMC/FDPClient/files/10833246/crash-2023-02-26_16.07.51-client.txt)

**Comment by ProSteveBedrock** [comment]
Still crashing even with DiscordRPC patch...

**Comment by ProSteveBedrock** [comment]
Thnks for trying to fix it.I gonna try it soon.

**Comment by ProSteveBedrock** [comment]
Thanks for update it works!!!
![Screenshot_2023-02-26-16-38-33-09_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/123849671/221400612-b99691fd-5c9c-424e-9d4a-1fbeaed10be6.jpg)
Keep up the good work thanks.

**Comment by ProSteveBedrock** [comment]
[Closing]
-It fixed!!!
