### ISSUE TITLE
[Bug] Proxy not working

### ISSUE THREAD

**Issue by Konzol** [SkidderMC/FDPClient#714]
when i try to join to a server with proxy i get an error `java.lang.NumberFormatException: For input string: "ip"`

**System Information**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - FDPClient Version: 5.2.0

**Comment by MatrixAura** [comment]
Stacktrace plz

**Comment by Konzol** [comment]
> Stacktrace plz

[latest.log](https://github.com/SkidderMC/FDPClient/files/10831134/latest.log)

**Comment by MatrixAura** [comment]
Is your proxy similar to x . x . x . x : x ?

**Comment by Konzol** [comment]
Oh sorry, i forgot the port 😅
