### ISSUE TITLE
[Bug] noslow无法在疾跑状态下工作 noslow can't work when you are printing

### ISSUE THREAD

**Issue by windmoon666** [SkidderMC/FDPClient#722]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
noslow无法在疾跑状态下工作 noslow can't work when you are printing

**To Reproduce**
1. 使用较新的FDPClient（5f5f8a0~最新版）   Use newer FDP Client（From 5f5f8a0 to lastest）
2. 进入游戏并打开noslow模块   Enter the game and open the noslow module
3. 在使用物品时疾跑将自动取消   It will automatically cancel sprint when u are using items

**Expected behavior**
在开启noslow时可以正常疾跑（达到正常疾跑的速度）   Don't cancel sprint when u are using items（Normal sprint when u are using items）

**Screenshots/Video**
我不知道如何在github上添加视频或图片   Sorry,I don't know how to add videos or pictures on github

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [Windows 11]
 - Minecraft Version: [1.8.9 forge]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [From 5f5f8a0 to lastest]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- None

**Additional info**
这次更新感觉问题有点多（我还会继续提交其他bug）
这是我第一次使用双语写错误报告，我英语不太好，先凑合着看吧

**Comment by contionability** [comment]
虽然但是，既然你自己知道会取消疾跑，那为什么不看一眼Sprint这个模块

**Comment by contionability** [comment]
我现在已经把很多疾跑逻辑设置成单独的选项了，包括使用物品时是否进行疾跑（UseItem / UseItemOnlySword）

**Comment by windmoon666** [comment]
对不起，当时没有往这方面想，谢谢解答

**Comment by iiCherry** [comment]
solution: delete fdpclient

**Comment by iiCherry** [comment]
Solution: Delete FDPClient
Thank me later :)
