### ISSUE TITLE
[Bug] 视线投射依旧不起作用 Raycast doesn't work

### ISSUE THREAD

**Issue by windmoon666** [SkidderMC/FDPClient#723]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
视线投射至今依旧是阵亡状态 Raycast doesn't work

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. 使用较新的FDPClient（5f5f8a0~最新版） Use newer FDP Client（From 5f5f8a0 to lastest）
2. 在杀戮光环模块里找到raycast   Find the raycast in the killaura module
3. 打开   Open it
4. 并没有出现任何其他选项（如ray cast Ignored或者living ray cast）   There isn't any other option appears (such us ray cast Ignored or living ray cast)
5. 打开了也没有任何效果   Nothing happened if u open it

**Expected behavior**
视线投射可以正常使用，不要死亡，这可以帮助使用者绕过很多反作弊   Ray cast can be used normally

**Screenshots/Video**
很抱歉我不知道如何在github上添加视频或图片   Sorry,I don't know how to add videos or pictures on github

**Crash Report**
If your game crashed, please paste your crash report below.

```text
[Paste Here]
```

**System Information**
 - OS: [Windows 11]
 - Minecraft Version: [1.8.9]
 - Forge Version: [11.15.1.2318]
 - FDPClient Version: [From 5f5f8a0 to lastest]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- None

**Additional info**
实现投射已经阵亡了好久了，希望Dev可以尽快修复他，这样使用者就可以方便的绕过非常多的反作弊
在5f5f8a0更新的vulcan strafe disabler真的很好用，可以用它绕过buzz、grimac等之前绕不过的反作弊

**Comment by contionability** [comment]
呃呃，我都说了修好了

**Comment by contionability** [comment]
现在完全就是按照原版逻辑进行Raycast，把多余的选项直接去掉了

**Comment by contionability** [comment]
自己配置问题
iq issue

**Comment by contionability** [comment]
It has been fixed bro
simply turn it on, I have removed useless options
now Raycast work like Vanilla, I have tested on OldAAC BAC and Buzz, it works perfectly

**Comment by windmoon666** [comment]
视线投射真的不起作用
[](url)

https://user-images.githubusercontent.com/107821597/221513561-63008f29-52e4-4e4c-82a3-06da8f648daf.mp4


这是我的杀戮
```
    "KillAura": {
      "state": false,
      "keybind": 19,
      "array": true,
      "autodisable": "NONE",
      "trigger": "TOGGLE",
      "values": {
        "MaxCPS": 11,
        "MinCPS": 6,
        "HurtTime": 10,
        "SimulateCooldown": false,
        "NoDuplicateAttack": false,
        "Range": 3.0,
        "ThroughWallsRange": 0.0,
        "RangeSprintReducement": 0.0,
        "SwingRange": 3.75,
        "DiscoverRange": 6.3,
        "BlinkCheck": false,
        "NoScaffold": true,
        "NoFly": true,
        "Priority": "Distance",
        "TargetMode": "Switch",
        "Swing": "Normal",
        "AttackTiming": "Pre",
        "KeepSprint": false,
        "NoBadPackets": false,
        "AutoBlock": "Range",
        "AutoBlockRange": 4.0,
        "BlockTiming": "Pre",
        "AutoBlockPacket": "Vanilla",
        "InteractAutoBlock": false,
        "BlockRate": 100,
        "RayCast": true,
        "RotationMode": "SmoothCenter",
        "MaxTurnSpeed": 48.65,
        "MinTurnSpeed": 32.77,
        "SmoothMode": "Sine",
        "CustomSmooth": 1.15,
        "RandomCenter": "Cubic",
        "RandomRange": 0.25,
        "RotationReverse": true,
        "RotationReverseTick": 15,
        "KeepDirection": true,
        "KeepDirectionTick": 15,
        "SilentRotation": true,
        "Strafe": "Silent",
        "Backtrace": false,
        "BacktraceTick": 10,
        "AlwaysHitAble": false,
        "FOV": 180.0,
        "Predict": true,
        "MaxPredictSize": 1.1,
        "MinPredictSize": 0.85,
        "PredictPlayer": true,
        "MaxPredictPlayerSize": 1.05,
        "MinPredictPlayerSize": 0.7,
        "FailRate": 0.0,
        "FakeSwing": true,
        "NoInvAttack": "Off",
        "NoInvDelay": 185,
        "SwitchDelay": 160,
        "LimitedMultiTargets": 0,
        "Mark": "FDP",
        "Circle": true,
        "CircleRed": 255,
        "CircleGreen": 255,
        "CircleBlue": 255,
        "CircleAlpha": 255,
        "CircleThickness": 2.7,
        "CircleRadius": 1.0
      }
    },
```

**Comment by windmoon666** [comment]
抱歉，点发布的时候不小心点到close了

**Comment by contionability** [comment]
额
因为这个Raycast会判断你是否开启了此类实体的target

**Comment by contionability** [comment]
那我干脆再加一个Option好了
选择是否忽略未选定实体

**Comment by contionability** [comment]
你再试试最新的那个构建
应该没问题了

**Comment by windmoon666** [comment]
链接寄了，等会再测试吧qwq
![a](https://user-images.githubusercontent.com/107821597/221545809-d127173f-c534-471b-a6af-f6e0853821fa.png)

**Comment by windmoon666** [comment]
2f25cfd的杀戮已经基本废了，完全无法正常使用，47937aa的还没有测试

**Comment by windmoon666** [comment]
测试完了，47937aa的也废了

**Comment by windmoon666** [comment]
目前发现的问题有：
1.array list的显示问题：

![image](https://user-images.githubusercontent.com/107821597/221550670-f540339f-28ca-4935-a2ad-444fdb5fbb71.png)

2.在range的距离中杀戮光环不会攻击目标：

![image](https://user-images.githubusercontent.com/107821597/221551559-f97896bd-4b23-43a7-a605-e043ba9bb450.png)

3.杀戮只会攻击正在discover range之内，range范围以外的目标（最远攻击6格）

![image](https://user-images.githubusercontent.com/107821597/221552318-6c096fb4-7964-4f7b-aa10-eb294be532e2.png)

4.手臂的挥动距离（swing range）由discover range决定而不是swing range

![image](https://user-images.githubusercontent.com/107821597/221554471-aa15dab4-a609-449e-bd42-4af3763886f0.png)
![image](https://user-images.githubusercontent.com/107821597/221554435-d13fea37-08fb-4b4a-af39-1e8209f6278c.png)

5.在没有打开always hit able时，就算视角没有转到可以攻击到目标的位置也会攻击到目标

![image](https://user-images.githubusercontent.com/107821597/221553953-dc64e146-0c37-4701-9e5d-b4d06c82e9b3.png)
![image](https://user-images.githubusercontent.com/107821597/221554108-d073fcff-e242-4555-97c5-8f30b725b8f3.png)

6.ray cast的判定只在range范围内生效

![image](https://user-images.githubusercontent.com/107821597/221554664-c0588fea-79fa-446b-bdc6-129107fad137.png)
![image](https://user-images.githubusercontent.com/107821597/221554717-510f427e-9c4a-4b73-9cf4-498444c9a369.png)
![image](https://user-images.githubusercontent.com/107821597/221556023-0488d42d-1627-40c4-b96d-9d1e1c1a4f92.png)
![image](https://user-images.githubusercontent.com/107821597/221554927-f406a162-02e3-4efb-9edc-149cd053cf8e.png)

**Comment by windmoon666** [comment]
感觉杀戮回滚到上一版然后再修改比较好，更新完杀戮之后问题太多了

**Comment by windmoon666** [comment]
而且这些问题出现的原因好像并不是因为你的更新，在9e179c6版本也有同样的错误

**Comment by windmoon666** [comment]
C2CA61F不存在这个问题，应该是9e179c6版本更新的问题

**Comment by windmoon666** [comment]
对不起，我收回上面说的话，C2CA61F版本也有关于杀戮的问题

**Comment by windmoon666** [comment]
C2CA61F版本的问题：
1.array list问题（跟上面一样，就不放图片了）
2.手臂的挥动距离（swing range）由Discover range决定而不是swing range（也不放图片了）

**Comment by windmoon666** [comment]
C2CA61F版本的问题：
1.array list问题（跟上面一样，就不放图片了）
2.手臂的挥动距离（swing range）由Discover range决定而不是swing range（也不放图片了）

**Comment by windmoon666** [comment]
D4F8FAC（不包括D4F8FAC）之后的所有版本的杀戮都或多或少有些问题

**Comment by contionability** [comment]
6
我这几天找时间仔细修修bug

**Comment by contionability** [comment]
干脆我稍微重写一下架构得了

**Comment by contionability** [comment]
难怪我贴脸经常没反应

**Comment by rsgikun** [comment]
> 干脆我稍微重写一下架构得了

6666shitshitshitcode

**Comment by contionability** [comment]
你有空的话帮我测测我自己这个配置吧
今天可能时间不太够

```
"KillAura": {
      "state": false,
      "keybind": 19,
      "array": true,
      "autodisable": "RESPAWN",
      "trigger": "TOGGLE",
      "values": {
        "MaxCPS": 20,
        "MinCPS": 20,
        "HurtTime": 10,
        "SimulateCooldown": false,
        "NoDuplicateAttack": false,
        "Range": 7.08,
        "ThroughWallsRange": 7.08,
        "RangeSprintReducement": 0.0,
        "SwingRange": 7.08,
        "DiscoverRange": 7.08,
        "BlinkCheck": true,
        "NoScaffold": true,
        "NoFly": false,
        "Priority": "Distance",
        "TargetMode": "Single",
        "Swing": "Normal",
        "AttackTiming": "Pre",
        "KeepSprint": true,
        "NoBadPackets": false,
        "AutoBlock": "Range",
        "AutoBlockRange": 7.08,
        "BlockTiming": "Pre",
        "AutoBlockPacket": "Vanilla",
        "InteractAutoBlock": false,
        "BlockRate": 100,
        "RayCast": true,
        "RaycastOnlyTarget": false,
        "RotationMode": "LockView",
        "MaxTurnSpeed": 360.0,
        "MinTurnSpeed": 356.82,
        "SmoothMode": "Line",
        "CustomSmooth": 1.0,
        "RandomCenter": "Cubic",
        "RandomRange": 0.29,
        "RotationReverse": true,
        "RotationReverseTick": 10,
        "KeepDirection": true,
        "KeepDirectionTick": 10,
        "SilentRotation": true,
        "Strafe": "Silent",
        "Backtrace": false,
        "BacktraceTick": 10,
        "AlwaysHitAble": true,
        "FOV": 180.0,
        "Predict": true,
        "MaxPredictSize": 1.0,
        "MinPredictSize": 1.0,
        "PredictPlayer": true,
        "MaxPredictPlayerSize": 1.0,
        "MinPredictPlayerSize": 1.0,
        "FailRate": 0.0,
        "FakeSwing": true,
        "NoInvAttack": "Off",
        "NoInvDelay": 200,
        "SwitchDelay": 0,
        "LimitedMultiTargets": 0,
        "Mark": "Jello",
        "Circle": true,
        "CircleRed": 255,
        "CircleGreen": 255,
        "CircleBlue": 255,
        "CircleAlpha": 255,
        "CircleThickness": 2.0,
        "CircleRadius": 1.0
      }
    },
```

**Comment by contionability** [comment]
在吗
你再试试看，这次应该是修好了
