### ISSUE TITLE
(Just ignore it) todo - list

### ISSUE THREAD

**Issue by contionability** [SkidderMC/FDPClient#728]
~NoChatClear - Done (not fully finished cuz Java limit)~
~Stop Server from clearing the chat message / stop server from closing the chat gui~

~NoChatLimit - Done~
~Disable the chat message length limit of 100 (customizable)~

~*ftr : Combine them together~
~including Chat Combine (Combined) / AntiSpammer (todo), etc~

Done

**Comment by contionability** [comment]
[*]
NoSlow Rewrite (Convert it to sub-modules structure)

**Comment by contionability** [comment]
[*]
MixinLayerCape
Fix Cape Glitching

**Comment by opZywl** [comment]
@contionability add support gif capes have this files but dont work
https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/ui/cape/GifCape.kt

**Comment by contionability** [comment]
ok

**Comment by contionability** [comment]
[*]
WallClimb Convert
AutoBlock Update
Fix Dynamic Cape
Fix Render FPS Drop

**Comment by contionability** [comment]
[*] TODO - 2023/03/18
Fix Sprint State update delayed 1 tick
Re-add AAC4.4 Step (WHO DELETE IT LMAO)

**Comment by Davidisnotavailable** [comment]
BACKTRACK fix pls
