### ISSUE TITLE
add sparky bypasses

### ISSUE THREAD

**Issue by gfddfgdgfdh** [SkidderMC/FDPClient#752]
yes? no? black?

**Comment by contionability** [comment]
Sparky is similar to Vulcan I think

**Comment by Davidisnotavailable** [comment]
Yes

**Comment by Davidisnotavailable** [comment]
it is kinda similar

**Comment by Syntex1337** [comment]
yes very similiar spinyfish told me
actually sparky is vulcan in disguise 😱 
spinyfish can confirm this info 100% guys

**Comment by C00LC0D35** [comment]
no
