### ISSUE TITLE
[Bug] Error in displaying simplified Chinese characters

### ISSUE THREAD

**Issue by HalfShadow111** [SkidderMC/FDPClient#757]
**Describe the bug**
Some Chinese characters in Simplified Chinese may be replaced by other characters when displayed.

**To Reproduce**
1. Open the game and enter a world.
2. Change the game language to Simplified Chinese.
3. Open the inventory or clickGUI.
4. Found that Chinese characters will be randomly replaced.

**System Information**
 - OS: Android 12
 - Minecraft Version: 1.8.9
 - Forge Version: 11.15.1.2318
 - FDPClient Version: 5.27

**Comment by C00LC0D35** [comment]
learn english or go fdpcn

**Comment by cdc12345** [comment]
> learn english or go fdpcn

sir，the main developer is chinese 

https://github.com/SkidderMC/FDPClient/issues/657
