### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by Darkingg12** [SkidderMC/FDPClient#761]
I'm having trouble importing modules from one version to another...

In the older version there is a module that allows me to bypass certain things on the server, I am able to move it to another (newer) but still old version of FDP.

Unfortunately, when I try to move the same module to the latest one - there is a problem ...
Some kind of blocking of modules or what?
I don't know if this can be done, but never mind... I don't publish it and don't sell it, I just modify it (but it's still FDP)

Is there any solution to this problem?
I would like to move an old module (Spider) from version 2.00 to 5.00

I am obsessed with this module..

Or maybe it's possible to make a separate script from this module? .class file to .js ?

BTW Sorry for my ENG..

**Comment by contionability** [comment]
so why don't you just tell me which bypass you want to add

**Comment by Darkingg12** [comment]
I was just thinking about advice, I didn't think that someone could get so involved...

I'm sending - one sec...

**Comment by Darkingg12** [comment]
I assure you that the hosting is safe :) - only Polish xd

http://hostuje.net/file.php?id=287e3748392aeea80a7b05181437e192
its this module

**Comment by Darkingg12** [comment]
And why is it now that if I replace a speed module with an older one, it is removed and is not in the menu?

I used to be able to remove the older speed and upload something from myself and even if it didn't do anything, it stayed in the menu anyway..

BTW sorry for my ENG x2

**Comment by Darkingg12** [comment]
Sooo..do you have any idea?
because I've been trying all day and I can't figure out why the error occurs..

**Comment by contionability** [comment]
cuz many things have changed bro
you have to make it compatible with the new system

**Comment by contionability** [comment]
cuz many things have changed bro
you have to make it compatible with the new system

**Comment by contionability** [comment]
also it make no sense that the old version bypassed and the new one didn't

**Comment by contionability** [comment]
btw, try to bypass using the new version
*I will check the src if I have time, maybe tonight

**Comment by contionability** [comment]
*you can see the error through Minecraft log

**Comment by Darkingg12** [comment]
new version too 
doesn't work

**Comment by Darkingg12** [comment]
I'll try to read what it's about
from logs

**Comment by Darkingg12** [comment]
can you include this module in the next update? I would be very grateful...

**Comment by contionability** [comment]
Only WallClimb?
I will convert the old modes if I have time tomorrow
you can tell me if there's anything else

**Comment by Darkingg12** [comment]
Only this :) 
I would be very grateful
and how would you send me this module after converting because I don't know where I could find it, unless you plan to put it with the new update?

**Comment by Darkingg12** [comment]
or a link when it's ready

BTW sorry my ENG

**Comment by contionability** [comment]
wait me until I have time (maybe Sunday)
I'm busy studying today.

**Comment by Darkingg12** [comment]
and by the way
do you know how to bypass the new matrix?
I'm talking about version 6.9.2...
specifically about killaura bypass because it keeps kicking me out...

**Comment by f4r2** [comment]
@Darkingg12 github shouldn't had gradle issues ig

**Comment by Darkingg12** [comment]
I don't know much about github
Can I post a topic like this on my profile in the sense of uncategorized in some section or somewhere?

will someone answer me then?

**Comment by contionability** [comment]
u need JDK 8 installed
then download the source code and type
.\gradlew build
in console (cmd or powershell)

**Comment by Darkingg12** [comment]
![obraz](https://user-images.githubusercontent.com/114777215/226852442-0fb19735-bfe9-46cf-b67d-7a54f5697aec.png)

comp has 4gb of ram, is that enough?

**Comment by Darkingg12** [comment]
when building fdp 5.1.0 with killaura module which is default in client everything builds fine but when i try to change killaura.kt to another killaura.kt client won't build... :(

here is killaura which is by default:
http://hostuje.net/file.php?id=b22d5278300a286386d56052269880d5

and this is the killaura I'm trying to replace:
http://hostuje.net/file.php?id=f26b689f6fa92e1948cbc365eddfa4cf

I know that these two files are slightly different,
this latest killaura is a bit "improved" but it needs the old one and I don't know what else to change to upload this older module..

**Comment by Darkingg12** [comment]
the error probably occurs in the "kotlin" stage... I know, I didn't listen in Java class but it's just one tiny module that I really need :))))))))

**Comment by contionability** [comment]
don't replace it by yourself as it requires basic knowledge of Kotlin language coding
Just find where the error is and try to fix it
![图片](https://user-images.githubusercontent.com/78670017/226918467-05794972-f35e-43e6-b209-9cb4eecabe00.png)

**Comment by Darkingg12** [comment]
error in what?
in the code of a specific module or gradlew version or something else?

![obraz](https://user-images.githubusercontent.com/114777215/226920038-7ceba15a-0e50-4d2f-a46d-e1482b5b71e7.png)


I'm assuming it's these lines

![obraz](https://user-images.githubusercontent.com/114777215/226920466-59c08700-6e83-49f5-af34-0bde8adad292.png)

![obraz](https://user-images.githubusercontent.com/114777215/226920615-ee4250ce-d652-4598-9751-e07f782c0fd1.png)


this is the only difference between these two modules, I can probably change the rest without fail..

if it's wrong it gives up.

what error did you mean? do you mean to change one specific thing in the code to the one i mean? :'''))

**Comment by Darkingg12** [comment]
I get a message that to change this module I need a newer gradle version (7.0)
apparently only then will I be able to build a client with the old module..

**Comment by contionability** [comment]
just ignore it

**Comment by contionability** [comment]
the actual problem is that your Kotlin compiler did not match the needed version
or maybe there's any other errors

**Comment by contionability** [comment]
![图片](https://user-images.githubusercontent.com/78670017/227548306-ef3bcdca-b1a6-448a-99d0-475e87c0c223.png)
The error message is above rather than below

**Comment by Darkingg12** [comment]
no difference anymore...
they changed the anti cheat in such a way that you have to be a god to get around this shit

**Comment by Darkingg12** [comment]
it is possible to make an aimbot that would work separately without lookview (the idea is to duplicate visions, aimbot aims at the opponent but I don't see it)
