### ISSUE TITLE
Perfomance Issue

### ISSUE THREAD

**Issue by MrBroken4U** [SkidderMC/FDPClient#763]
Fdp Lag too much

**Comment by ProSteveBedrock** [comment]
Yeah Rise Client is even Smoother that FDPClient .... Fix.(Suggest: Make lite version LoL).

**Comment by f4r2** [comment]
this is because mixins
u can try to remove them but thats hard @ProSteveBedrock

**Comment by opZywl** [comment]
lmao wdr5ftwyghduijkowldw;d
