### ISSUE TITLE
[Bug] Font not found

### ISSUE THREAD

**Issue by pierrelasse** [SkidderMC/FDPClient#765]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Tryna to load font but path not found

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Get fornite battle pass
2. Shit out your ass
3. Boot up your pc
4. Boot up fdp client
5. See the logs
6. Get Spammed

**Expected behavior**
Checking if file exists and if not then no load da font

**Screenshots/Video**
If applicable, add screenshots, or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/76223390/225863757-88005046-2fbc-4fca-b2f0-af104f816ded.png)

**Crash Report**
If your game crashed, please paste your crash report below.
no crash?

```text
[Paste Here]
[Paste Here]
[Paste Here]
[Paste Here]
```

**System Information**
 - OS: [e.g. Windows 10]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. idk the star 1 in multimc]
 - FDPClient Version: [e.g. newest beta but is on old ver too]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Idk optiofine and worldeidt and viaforg

**Additional info**
I hate to take shit bec taking too long

**Comment by f4r2** [comment]
u need to put sf.ttf in fdp fonts

**Comment by pierrelasse** [comment]
but i dont want to and there are much fonts not loading

**Comment by pierrelasse** [comment]
why is this fkingclosing

**Comment by pierrelasse** [comment]
why is it not reopneing

**Comment by pierrelasse** [comment]
ah :D

**Comment by f4r2** [comment]
download fonts from https://github.com/SkidderMC/FDPClient/tree/main/src/main/resources/assets/minecraft/fdpclient/font and put them to fonts in fdp folder

**Comment by pierrelasse** [comment]
ok anyways it is doing that for like 50 fonts

**Comment by f4r2** [comment]
do what i said if it still not work than download fonts from other site because not all fonts are included on that

**Comment by f4r2** [comment]
kk

**Comment by f4r2** [comment]
i mean when u even do that u can still get errors because idk why
fdp is bugged but u can just ignore them

**Comment by pierrelasse** [comment]
SF.ttf or lowercase?

**Comment by f4r2** [comment]
download all them and do 2 SF.ttf one lower case and one uppercase

**Comment by f4r2** [comment]
ye its cool that its dynamic

**Comment by pierrelasse** [comment]
ok it is doing this for much fonts

**Comment by pierrelasse** [comment]
nstances\FDP\.minecraft\FDPCLIENT-1.8\fonts\stylesicons.tt
DP\.minecraft\FDPCLIENT-1.8\fonts\Roboto-Medium.tt
es\FDP\.minecraft\FDPCLIENT-1.8\fonts\Roboto-Medium.ttf (Das System kann die angegebene Datei nicht finden)

and so on

**Comment by f4r2** [comment]
download roboto medium from https://fonts.google.com/specimen/Roboto its not included

**Comment by f4r2** [comment]
also do what randomguy said in chat-en

**Comment by f4r2** [comment]
i guess u need to edit fonts.json too
