### ISSUE TITLE
[Bug] .bind command

### ISSUE THREAD

**Issue by rikoshet185** [SkidderMC/FDPClient#766]
*".bind module" stopped working after version ~3.0,
 If you try to use the command now, Enter will always be selected as the bind
I'm surprised why it hasn't been fixed to this day.

**System Information**
 - OS: [e.g. Windows 7]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.1764]
 - FDPClient Version: [e.g. 3.0-Latest]

**Other Installed Mods**
- OptiFine HD U M5
- ViaForge "1.8.9 for 1.19"
I wrote through a translator, there may be grammatical errors

**Comment by C00LC0D35** [comment]
... you do .bind [module] [key]
????
