### ISSUE TITLE
[Bug] Non-working modules, bypasses

### ISSUE THREAD

**Issue by rikoshet185** [SkidderMC/FDPClient#767]
MatrixWater Highjump does not work completely, why was it returned after deletion?
Packet Tower is broken, I tested on NCP. It worked well with LiquidBounce. with fdp, the player just stood still.
AAC 3.0.5 Fly does not work at all on AAC 3.0.5 and on AAC 3.0.4,(but 3.3.12 fly works) I have tested and can write down the proofs if necessary.
AAC 3.3.12 Fly was deleted by a completely retarded person because he still bypasses a couple of servers
Why AAC 1.9.10 Fly when there is a disabler in LB Nextgen?
Longjump is completely broken due to the global timer
Rename the AirLadder to FastLadder, obviously why
Rename the bypasses to Redesky. Redesky is no more.
NCPPacketFly does not work at all on NCP
OldMatrix rotation in killaura does not bypass any version of the matrix
The "Test" names in the modules remained from the very beginning of the fdp. (scaffold, and Noweb)
All Regens modes except vanilla do not work at all
AutoSoup does not work with ViaForge on 1.12
AAC4.2.6 Jesus is buggy, starts jumping after use, and by itself does not bypass at least some servers
SpoofGround Antivoid starts to flag after use
New MatrixBoost Fly - not Fly
Killinsults are not supported in diffirent language
HypSpoof Nofall doesn't bypass anything
**Other Installed Mods**

- ViaForge
- OptiFine

I wrote this through a translator, there may be grammatical errors

**Comment by C00LC0D35** [comment]
cope!!

**Comment by C00LC0D35** [comment]
ok: packet tower works for me
      longjump works for me
 
aac 3 3 12 readded
ncp packetfly used to work on blockdrop
old matrix is removed
scaffold rots renamed

spoofground is meant to flag 💀 

hypixel antivoid fixed

regen modes do work, they are just very subtulbe, u need hundreds of packets to noticables regen faster (it flags timer hella lot)

redesky longjump modes have legacy warning

matrix boost fly is a fly

hypspoof removed

**Comment by contionability** [comment]
BRO, AAC3.0.5Fly works when you fall into void

**Comment by contionability** [comment]
and why using AAC3.0.5 Fly in 2023

**Comment by contionability** [comment]
https://www.youtube.com/watch?v=6B63__w3LZg

**Comment by contionability** [comment]
@C00LC0D35 Don't do what he says
He said a lot of wrong things
@rikoshet185 A Bypass doesn't necessarily have to correspond to its AntiCheat
that's the basic principle of Bypass

**Comment by contionability** [comment]
If I told you AAC1.9.10 Fly Bypassed OldVulcan and Frequency, what do you think?

**Comment by contionability** [comment]
also If I told you NCPPacketFly Bypassed BlockDrop?

**Comment by contionability** [comment]
HypSpoof Bypassed Matrix, Frequency, Spartan

**Comment by contionability** [comment]
SpoofGround is meant to flag in order to Antivoid

**Comment by contionability** [comment]
OldMatrix Bypassed Matrix 5.X.X with FakeLag Disabler (Full Bypassed with MultiAura)
also Bypassed Vulcan AimQ Check

**Comment by contionability** [comment]
Longjump GlobalTimer works normally, some Anticheat need lower timer to bypass

**Comment by contionability** [comment]
AirLadder makes you climb up a ladder even when you're not collided with ladder

**Comment by contionability** [comment]
and due to the packet difference
AutoSoup cannot work on 1.12.2

**Comment by contionability** [comment]
I will fix AAC4.2.6 Jesus and Regen
As for the rest, you need to understand the basic principles of "Bypassing" first

**Comment by rikoshet185** [comment]
Understood. I'll check everything again during the day

**Comment by contionability** [comment]
anyways, if a bypass is Unbypassable, that's OK and you don't need to tell
but if a bypass doesn't work at all (or not working properly), such as Regen, you can open a issue

**Comment by rikoshet185** [comment]
About packet tower, I was partially mistaken, it did not work on 3.0-4.6.5. But now it is working
About longjump, what timer did you set to bypass MatrixFlag?
NCPPacketFly  if it does not work on nsp (I tested), then why does it have such a name?
New MatrixBoostFly, exactly the new one, cannot be used as a fly, exclusively as a longjump
And also, why was my previous bug report deleted, I was talking about ".bind module", not about ".bind module key".

**Comment by rikoshet185** [comment]
"If I told you AAC1.9.10 Fly Bypassed OldVulcan and Frequency, what do you think?"
There are a ton of flyers and teleports on the old vulcan
Frequency is nowhere to be found, this is the first time I've heard of such an anti-cheat
moreover, this fly is from lb, its anti-cheats are fixed in priority

**Comment by Darkingg12** [comment]
what about killaur bypass?
Can anyone recommend some settings that won't throw me on the matrix?

**Comment by rikoshet185** [comment]
I didn't notice absolutely any functions in AirLadder before adding YMotion

**Comment by contionability** [comment]
oh I saw that issue (keybind)
I will fix

**Comment by C00LC0D35** [comment]
> @C00LC0D35 Don't do what he says He said a lot of wrong things @rikoshet185 A Bypass doesn't necessarily have to correspond to its AntiCheat that's the basic principle of Bypass



> @C00LC0D35 Don't do what he says He said a lot of wrong things @rikoshet185 A Bypass doesn't necessarily have to correspond to its AntiCheat that's the basic principle of Bypass

lol what
