### ISSUE TITLE
Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by Dominus12k** [SkidderMC/FDPClient#771]
When I try to open up Minecraft it says Error: could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit. I don't know why this is happening I have the fdp jar in my mods folder and I have 1.8 forge installed.

**Comment by pierrelasse** [comment]
OS?, Launcher?, other mods?, tried without fdp mod?, took a shit?
