### ISSUE TITLE
About killaura 

### ISSUE THREAD

**Issue by Tritiko** [SkidderMC/FDPClient#777]
killaura autoblockpacket Vanilla + noslow vulcan/grima等有时会爆autoblock（order）有时不会爆
环境：FDPClient v 5.3.0 今天的最新版 反作弊测试服mc.stitch.best 下的 vulcan
![autoblock](https://user-images.githubusercontent.com/113193082/227770033-35845d6b-0b0d-418c-84c9-8fb32c8c56a0.png)
killaura throughwallsrange 不正确工作，不受控制一直穿墙打人

**Comment by StupidQu** [comment]
> killaura autoblockpacket Vanilla + noslow vulcan/grima等有时会爆autoblock（order）有时不会爆 环境：FDPClient v 5.3.0 今天的最新版 反作弊测试服mc.stitch.best 下的 vulcan ![autoblock](https://user-images.githubusercontent.com/113193082/227770033-35845d6b-0b0d-418c-84c9-8fb32c8c56a0.png) killaura throughwallsrange 不正确工作，不受控制一直穿墙打人

我无法复现这个问题，请问你可以将你的 Killaura 设置发出来吗？或发一个演示视频。

**Comment by Tritiko** [comment]
> > killaura autoblockpacket Vanilla + noslow vulcan/grima等有时会爆自动block（order）有时不会爆 环境：FDPClient v 5.3.0 今天的最新版 反作弊测试服mc.stitch.best 下的 vulcan ![自动阻止](https://user-images.githubusercontent.com/113193082/227770033-35845d6b-0b0d-418c-84c9-8fb32c8c56a0.png) killaura throughwallsrange 不正确工作，不受控制一直穿墙打人
> 
> 我无法复现这个问题，请问你可以将你的 Killaura 设置发出来吗？或发一个演示视频。

[hypixel.zip](https://github.com/SkidderMC/FDPClient/files/11711278/hypixel.zip)
抱歉现在才看到，这同样适用于最新FDP，目前只有修复才能绕过hypixel autoblock了
