### ISSUE TITLE
[Bug] C07PacketPlayerDigging BadPackets

### ISSUE THREAD

**Issue by supercellgamer** [SkidderMC/FDPClient#779]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
There is a line of code within FDP which sends the C07PacketPlayerDigging packet RELEASE_USE_ITEM with a flagging BlockPos
it sends a BlockPos of (-1, -1, -1) instead of (0, 0, 0) which is the only legit packet for the RELEASE_USE_ITEM action

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. Enable autoblock in killaura
2. Walk towards a player
3. When you begin autoblocking walk away
4. Send a bad packet

**Expected behavior**
It shouldn't send that kind of thing... just a small fix should be good. The issue I found is this flags on GrimAC

**Screenshots/Video**
Here is a small example image
https://meteor.token-logger.click/f8l0goee.png

**Comment by AntidisestablishmentarianismIsReal** [comment]
https://github.com/SkidderMC/FDPClient/pull/835 fixed by this. someone please close
