### ISSUE TITLE
[Bug] GrimAC NoSlow bypass

### ISSUE THREAD

**Issue by supercellgamer** [SkidderMC/FDPClient#781]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
NoSlow with GrimAC mode not only switches items (as it should) but also sends post place block packets which flags grim

**To Reproduce**
<Steps to reproduce the behavior (how did you get this bug to occur):>
1. set noslow packet mode to GrimAC
2. enable
3. block with a sword
4. flag

**Expected behavior**
removing or adding a better exception would fix it

**Screenshots/Video**
https://meteor.token-logger.click/5vxw2lei.png
https://meteor.token-logger.click/zb168wfd.png

**Comment by C00LC0D35** [comment]
use swtich item noslow, that one actually works

**Comment by Davidisnotavailable** [comment]
or use glitch
