### ISSUE TITLE
<Please Skid>To compare copy and paste techniques with him

### ISSUE THREAD

**Issue by MatrixU5er** [SkidderMC/FDPClient#787]
https://github.com/Aspw-w/NightX-Client/blob/master/src/main/java/net/aspw/client/features/module/modules/movement/Flight.kt
Vulcan3 fly

**Comment by C00LC0D35** [comment]
vulcan damage you retard

**Comment by MatrixU5er** [comment]
OK the fly look like not need damage ;/
