### ISSUE TITLE
Aura is broken tf

### ISSUE THREAD

**Issue by HanfHaase** [SkidderMC/FDPClient#805]
After a while the aura doesn't attack anymore and I have to hit the player without once to make it work again.
https://youtu.be/HpzOpEKWt6I Here is a video

**Comment by Davidisnotavailable** [comment]
could you send me your config i want to take a look

**Comment by HanfHaase** [comment]
https://www.mediafire.com/file/no8abwd6pce0f16/VisuelTEST.json/file

Sorry for waiting
