### ISSUE TITLE
[Bug] Killaura FPS Problems

### ISSUE THREAD

**Issue by jinshastudios** [SkidderMC/FDPClient#829]
Enable Killaura FPS will down to 10-60
Disable=200+FPS
So wt?
Log seems like motion bug...

**Comment by Davidisnotavailable** [comment]
delete your .mincraft folder if you got latest Action (safe configs if you want to)
or update to latest action 
i also had that problem

**Comment by SwatZeer** [comment]
I tried to reinstall EVERYTHING it but also like this...
fdp 5.28 after???
so how 2 solve this issues?
