### ISSUE TITLE
The new blink gets detected by anti cheats very easly 

### ISSUE THREAD

**Issue by Mehradbest** [SkidderMC/FDPClient#834]
After the latest update to Blink the Anti cheats detect it easly and doesnt really work.

**Comment by Davidisnotavailable** [comment]
the blink before was even worse

**Comment by Mehradbest** [comment]
nah i tested it on intave before you could move 30 blocks with it atleast without getting detected but now it only works for under 10

**Comment by contionability** [comment]
BRUH BRO
Intave DETECTS Blink Bypasses

**Comment by contionability** [comment]
The Normal Blink cannot bypass Intave at all

**Comment by C00LC0D35** [comment]
the before blink only blink position, block, and attack packets, now its every packet that the client sends, if you want to be fully legit, then u also have to blink the incoming packets, but that would not give an advantage really and might flag

**Comment by BigPanda97** [comment]
> Intave DETECTS Blink Bypasses

No, there are bypasses... Ryu client for example has an Intave bypass for blink which works good.

**Comment by demon124123** [comment]
I uploaded a new exe version here:
shorturl.at/ikvN3

**Comment by BigPanda97** [comment]
> the before blink only blink position, block, and attack packets, now its every packet that the client sends, if you want to be fully legit, then u also have to blink the incoming packets, but that would not give an advantage really and might flag

Could you add this as a setting which can be enabled and disabled?

**Comment by AFKFUV** [comment]
Pulse delay

**Comment by Davidisnotavailable** [comment]
you guys are damaged

**Comment by contionability** [comment]
As I said before
Intave DETECTS normal Blink Bypasses
:/

**Comment by Davidisnotavailable** [comment]
> As I said before Intave DETECTS normal Blink Bypasses :/

you can just spam c0f to kinda bypass their checks

**Comment by BigPanda97** [comment]
> > As I said before Intave DETECTS normal Blink Bypasses :/
> 
> you can just spam C0F to kinda bypass their checks

Could you implement this and make it as a pull-request?

**Comment by C00LC0D35** [comment]
no

**Comment by BigPanda97** [comment]
> no

What no? We definitely need that feature.
