### ISSUE TITLE
[Bug] <BackTarck>

### ISSUE THREAD

**Issue by a114mc** [SkidderMC/FDPClient#848]
1.BackTrack 不工作

2.无法启动 FDP5.3.5 Beta 29402e6

备注：
启动游戏用的 [java JRE: 8.0.371]
另外一个 [Java JDK: 17.0.7]
游戏启动器：PCL2 2.6.1

**Comment by a114mc** [comment]
顺带说一句，好像FDPClient的构建依赖JAVA Pakcet200 
![98fec1a67330f172b0f9e0d1d1efcd2](https://github.com/SkidderMC/FDPClient/assets/134874282/d7bd738e-00d5-4824-a366-ba9353dedd8d)

**Comment by Davidisnotavailable** [comment]
JDK Installer java 1.8 to build fdp: ![Download](https://workupload.com/file/NCXP6vLJtUp) 
go to the settings 
![image](https://github.com/SkidderMC/FDPClient/assets/101277472/1d34db7f-c933-4950-b7d9-bccf232efb9d)

open project structure
change the SDK to the java oracle 1.8

go again to settings
 ![image](https://github.com/SkidderMC/FDPClient/assets/101277472/1d34db7f-c933-4950-b7d9-bccf232efb9d)

 settings (under project structure)
 
 find this
![image](https://github.com/SkidderMC/FDPClient/assets/101277472/a449f456-7298-44f0-98af-8107cabfd75e)
click on gradle

![image](https://github.com/SkidderMC/FDPClient/assets/101277472/e15b610e-d605-42f6-a5cc-a5f68d09470b)
find this 
and change it again to java 1.8 
and it should work (building and stuff)
