### ISSUE TITLE
Blink cancel like other clients

### ISSUE THREAD

**Issue by BigPanda97** [SkidderMC/FDPClient#854]
FDP should have a ".blink cancel" command like the most other clients to cancel blink without sending packets, for example if you fall down into the void while you use blink.

**Comment by C00LC0D35** [comment]
uh.. What?

**Comment by BigPanda97** [comment]
> uh.. What?

If you use "Blink", but fall down into the void, then you die when disabling Blink, because it sends the packets....... but other clients have a command like ".blink cancel" to throw away the saved packets and disable Blink instead of sending the packets.

Like: https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/systems/modules/movement/Blink.java

**Comment by C00LC0D35** [comment]
ok

**Comment by BigPanda97** [comment]
@C00LC0D35  Sorry, but this is still somehow buggy. Have you tried it?
It doesn't disable the blink module, so you still have to disable it manually after sending the chat command; and sometimes it still teleports you and sometimes it sets you back but does not remove the fake-player and the breadcrumb-line.
Thanks for your help.

**Comment by BigPanda97** [comment]
> @C00LC0D35  Sorry, but this is still somehow buggy. Have you tried it?
> It doesn't disable the blink module, so you still have to disable it manually after sending the chat command; and sometimes it still teleports you and sometimes it sets you back but does not remove the fake-player and the breadcrumb-line.
> Thanks for your help.

@C00LC0D35 ?
