### ISSUE TITLE
Conflict with 3D skin

### ISSUE THREAD

**Issue by SeekIT001** [SkidderMC/FDPClient#856]
As shown in the question, installing FDP while also installing Forge 3D skin will result in not displaying double skin, **only single skin**

**Comment by B4mb0u** [comment]
then just fix your fucking client and don't reply that shit retard

**Comment by Davidisnotavailable** [comment]
> then just fix your fucking client and don't reply that shit retard

fix it by yourself you are the only one who got this problem we wont care about this shit

**Comment by B4mb0u** [comment]
damn you're fast

**Comment by C00LC0D35** [comment]
!!retard altert!!
!!retard altert!!
