### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by PitPot1** [SkidderMC/FDPClient#857]
Not sure if this is the right place to leave suggestions but im gonna do it anyway

- Fix moving while killaura is attacking someone flagging some anticheats (GrimAC, AAC, Hawk...) its fine if it dosent let you move freely, atleast it will work (or make it a togglable fix because it still bypasses many anticheats)

- Add a REAL no strafe mode to custom speed (the current one still gives you strafe for some reason)

- Add a balance mode to timer (example: timer is at 0.1 for 1s then goes to 2 for 1 second and repeat, this makes it bypass some anticheats)

**Comment by C00LC0D35** [comment]
go to bypass options and go to strafe fix (or smth ) and set mode to silent (or strict if u want to 0 flag)

just use legit speed

ill add balance mode soon ™️
