### ISSUE TITLE
[Bug] java.lang.StackOverflowError: Initializing game Crash when finished startup

### ISSUE THREAD

**Issue by HowardZHY** [SkidderMC/FDPClient#858]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
java.lang.StackOverflowError: Initializing game

**To Reproduce**
1. 5.3.5+Forge 2318

**Expected behavior**
No Crash

**Crash Report**
If your game crashed, please paste your crash report below.

[crash-2023-06-13_02.53.18-client.txt](https://github.com/SkidderMC/FDPClient/files/11727161/crash-2023-06-13_02.53.18-client.txt)
[fml-client-latest.log](https://github.com/SkidderMC/FDPClient/files/11727176/fml-client-latest.log)

**System Information**
 - OS: [e.g. Windows 11]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [Latest Release]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.
- Optifine, InputFix, DamageIndicators

**Comment by C00LC0D35** [comment]
try removing the other mods

**Comment by HowardZHY** [comment]
Weird it doesn't happen after I installed a new Forge instance
