### ISSUE TITLE
[Bug] Crash with BetterFPS

### ISSUE THREAD

**Issue by HowardZHY** [SkidderMC/FDPClient#860]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
Crashes when finishing startup

**To Reproduce**
1. Latest FDP with Better FPS 1.2.0
2. Crash

**Expected behavior**
No Crash

**Crash Report**
If your game crashed, please paste your crash report below.
[crash-2023-06-13_13.17.37-client.txt](https://github.com/SkidderMC/FDPClient/files/11730844/crash-2023-06-13_13.17.37-client.txt)

[fml-client-latest.log](https://github.com/SkidderMC/FDPClient/files/11730839/fml-client-latest.log)

**System Information**
 - OS: [Windows 11]
 - Minecraft Version: [e.g. 1.8.9]
 - Forge Version: [e.g. 11.15.1.2318]
 - FDPClient Version: [5.3.5]

**Other Installed Mods**
If you have any other mods installed, please list them here along with their version number.

**Additional info**
LB doesn't crash

**Comment by C00LC0D35** [comment]
wtf is better fps, use optifine or sum normal

**Comment by HowardZHY** [comment]
> wtf is better fps, use optifine or sum normal

It's very common pre 1.12.2 mod

**Comment by HowardZHY** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/betterfps
