### ISSUE TITLE
Grim Velocity got fixed – new bypasses?

### ISSUE THREAD

**Issue by BigPanda97** [SkidderMC/FDPClient#871]
They fixed our Grim Velocity module right here: https://github.com/GrimAnticheat/Grim/issues/1056

Are there any ideas for a new AntiKB which works on GrimAC?

**Comment by MWHunter** [comment]
No idea

**Comment by c0dingnoobi** [comment]
> our Grim Velocity

"our"
rip baldo

**Comment by Davidisnotavailable** [comment]
> They fixed our Grim Velocity module right here: [GrimAnticheat/Grim#1056](https://github.com/GrimAnticheat/Grim/issues/1056)
> 
> Are there any ideas for a new AntiKB which works on GrimAC?

use attackreduce velo

**Comment by MWHunter** [comment]
Will be sure to take a look at that later tonight

**Comment by ytnoos** [comment]
Make sure to not tell the next bypass to Grim's dev

**Comment by BigPanda97** [comment]
> Make sure to not tell the next bypass to Grim's dev

The client is open source, so that's not possible...
