### ISSUE TITLE
How to change the icon and the background schreen of Fdp<Title Here>

### ISSUE THREAD

**Issue by Yousaf1796** [SkidderMC/FDPClient#876]
Hello sir, I hope you're doing well. I appreciate your work. However, I have encountered a problem. My friend from SMP (Survival Multiplayer) suggested that I share my screen with them, but since I'm using an FDP client, I am unable to do so. Therefore, I need your help with three things. Firstly, could you please guide me on how to change the icon? Secondly, I would like to know how I can change my name. Whenever I open the game, it displays my FDP name and a GitHub link. Lastly, I'm wondering how I can change the background to a normal one. I'm eagerly awaiting your response and I would be extremely grateful for your assistance. Thank you for your kindness in advance.

**Comment by C00LC0D35** [comment]
use raven b+ or sum at this point

**Comment by Yousaf1796** [comment]
> ommented

not have money to buy vape

**Comment by MatrixAura** [comment]
> > ommented
> 
> not have money to buy vape

you can download vape cracked(4.04 or 4.10)

**Comment by Davidisnotavailable** [comment]
> > > ommented
> > 
> > 
> > not have money to buy vape
> 
> you can download vape cracked(4.04 or 4.10)

never download cracks
