### ISSUE TITLE
"Center" mode for Tower

### ISSUE THREAD

**Issue by BigPanda97** [SkidderMC/FDPClient#881]
I have noticed that many tower modes of Scaffold flag, when you are standing between two blocks or not correctly centered. There should be a tower option like “MoveToCenter” or so which automatically moves you to the center of the block you're standing on to prevent such flags and work more flawlessly. (Should still be compatible with Safewalk and not move you into the void when standing between a block and air/void.)
And by the way: There could also be a config option to automatically stop towering when there is a block above your head, to prevent flagging and bugs when towering is just physically not possible.

**Comment by C00LC0D35** [comment]
pov you didnt see the stopwhenblockabovehead option.

**Comment by BigPanda97** [comment]
> pov you didnt see the stopwhenblockabovehead option.

Oops, found it. But the main idea still exists with the center feature.
