### ISSUE TITLE
some stuff fdp needs

### ISSUE THREAD

**Issue by Manudha1212** [SkidderMC/FDPClient#898]
add some modules like

vulcan disabler
verus disabler
ncp semi disabler 
anticheat finder - that finds what the anticheat server using commands like if its vulcan /vulcan so it says u dont have permissions
blocksmc fly - like rise fly
ncp blatant speed
.panic which toggles every cheat its specially made for clients like semi blatant injectable clients but this could be usefull

and skid from rise 6 since rise 6 gets cracked every release in 30 minutes hehe :100:

**Comment by C00LC0D35** [comment]
1, no one uses vulcan. 2, No one uses verus. 3, anticheat finder is for people with no friends. 4, rise6 getting cracked doesnt mean src is cracked, and we dont skid

**Comment by Davidisnotavailable** [comment]
> 1, no one uses vulcan. 2, No one uses verus. 3, anticheat finder is for people with no friends. 4, rise6 getting cracked doesnt mean src is cracked, and we dont skid

but i will skid uwu :3

**Comment by BigPanda97** [comment]
> 2, No one uses verus.

LibreCraft (and as far as I know, BlocksMC too) use Verus + NCP + old Matrix.

**Comment by Cosmic-SC** [comment]
> 1, no one uses vulcan. 2, No one uses verus. 3, anticheat finder is for people with no friends. 4, rise6 getting cracked doesnt mean src is cracked, and we dont skid

"and we dont skid" yeah ok bro (real) :skull:

**Comment by C00LC0D35** [comment]
prove where skid?

**Comment by Cosmic-SC** [comment]
> prove where skid?

you are the skid :skull:
