### ISSUE TITLE
Add another TickBase module

### ISSUE THREAD

**Issue by BigPanda97** [SkidderMC/FDPClient#900]
The TickBase of the official LiquidBounce client has many other options than our current one, which could be needed to bypass some anti-cheats. However, I would not recommend replacing our current one. It would be better to add this as a new, seperate module. Src: https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleTickBase.kt

**Comment by Davidisnotavailable** [comment]
they use competly different utils it sucks

**Comment by Davidisnotavailable** [comment]
and the current one does bypass anticheat

**Comment by BigPanda97** [comment]
> and the current one does bypass anticheat

But the other one seems to have more settings, which is always nice...

> they use competly different utils it sucks

Then... what about merging their TickBase into ours to improve ours even more?
