### ISSUE TITLE
It may be worth learning about               

### ISSUE THREAD

**Issue by LineOpng** [SkidderMC/FDPClient#917]
https://github.com/MatrixAura/Rise
https://github.com/play-hanabi/hanabi-client
https://github.com/SuperSkidder/OpenHanabi
https://github.com/RE-KevinClient/KevinClient-Reborn/releases
https://kgithub.com/StephenIsTaken/Raven-BPlusPlusPlus/releases/tag/v1.4
Tenacity 5.1 src leak https://wwwu.lanzouj.com/iwsoH11pmcda

**Comment by MatrixAura** [comment]
oops

**Comment by vPrah** [comment]
Skidding 💀
