### ISSUE TITLE
I want AimBot to target players with stealth effects.

### ISSUE THREAD

**Issue by BaiJiu123** [SkidderMC/FDPClient#949]
Sometimes, we usually PVP with the player, the other player drink stealth potion, this time, FDP AimBot will not lock, I have turned on anti-stealth, but just can not lock the player.
    So I want to make a series of modules like Aimbot that can target stealth players.
    It is also hoped that Velocity can bypass Karhu Anticheat.

**Comment by MatrixAura** [comment]
antibot problem lol
