### ISSUE TITLE
Please add always spoof ground nofall back 

### ISSUE THREAD

**Issue by kokqi** [SkidderMC/FDPClient#950]
Here's the reason why you should add it back, fly can bypass Themis if the always spoof ground nofall is combine with minemora fly  
https://streamable.com/lsfygg?src=player-page-share 

Oh btw scaffold is unnecessary, since I just use it to showcase the speed bypass

**Comment by kokqi** [comment]
nvm always spoof is basically always spoof ground

**Comment by ManInMyVan** [comment]
> nvm always spoof is basically always spoof ground
> 

Then close the issue?
