### ISSUE TITLE
Add a grim fly?

### ISSUE THREAD

**Issue by minecraftmoderso** [SkidderMC/FDPClient#957]
lime and nursultan client both have grim Flies so i was wondering if you guys could add it as an update

Nursultan -> https://youtu.be/v0DcMgdeanU
Lime -> https://youtu.be/LAF0rDkkTgU

**Comment by RtxOP** [comment]
May I ask what you used to packet log?

**Comment by Davidisnotavailable** [comment]
> May I ask what you used to packet log?

packets

**Comment by C00LC0D35** [comment]
use blockdrop or smthertghn

**Comment by Davidisnotavailable** [comment]
> use blockdrop or smthertghn

doesnt work

**Comment by RtxOP** [comment]
> > use blockdrop or smthertghn
> 
> doesnt work

use 1.17+

**Comment by Davidisnotavailable** [comment]
> > > use blockdrop or smthertghn
> > 
> > 
> > doesnt work
> 
> use 1.17+

if you use viaversion or something you just get flags 40 times/sec

**Comment by RtxOP** [comment]
> > > > use blockdrop or smthertghn
> > > 
> > > 
> > > doesnt work
> > 
> > 
> > use 1.17+
> 
> if you use viaversion or something you just get flags 40 times/sec

Exactly. Because the packets viaversions sends arent legit

**Comment by RtxOP** [comment]
Have fun recoding it

**Comment by Davidisnotavailable** [comment]
> Have fun recoding it

no

**Comment by yfishyon** [comment]
you can use js

**Comment by minecraftmoderso** [comment]
> you can use js

do you have a js script?
