### ISSUE TITLE
Add velcoity for HuaYuTing sever

### ISSUE THREAD

**Issue by Genius114514** [SkidderMC/FDPClient#967]
Hello,I am one of your fdp client user from China.The Largest server in china is HuaYuTing(1.12.2).We are very happy that your client has a nice versionfix and may be 3 weeks ago,we using the js to bypass this severs's telly scaffold.But just 5 days this severs anticheat was updataed.All velocity modes have been fixed.Before this updataed,we using the grim velocity to killing other hacks.Why did us choose fdp?We are looking for your 100% ab!By the way the anticheat is Grim.Also nursultan client form Russia can bypass the velocity.You can learn from it ：）
If you do this,I thinks the user form china will be more

**Comment by tianxily** [comment]
不用啊，C07全反不都泛滥了吗？

**Comment by Xcating** [comment]
`package net.ccbluex.liquidbounce.features.module.modules.combat

import net.ccbluex.liquidbounce.event.*
import net.ccbluex.liquidbounce.features.module.Module
import net.ccbluex.liquidbounce.features.module.ModuleCategory
import net.ccbluex.liquidbounce.features.module.ModuleInfo
import net.ccbluex.liquidbounce.injection.backend.unwrap
import net.ccbluex.liquidbounce.utils.ClientUtils
import net.ccbluex.liquidbounce.utils.MovementUtils
import net.ccbluex.liquidbounce.value.BoolValue
import net.ccbluex.liquidbounce.value.IntegerValue
import net.ccbluex.liquidbounce.value.ListValue
import net.minecraft.entity.EntityLivingBase
import net.minecraft.network.Packet
import net.minecraft.network.play.INetHandlerPlayClient
import net.minecraft.network.play.server.*
import net.minecraft.network.play.client.*
import net.minecraft.util.EnumFacing
import net.minecraft.util.math.BlockPos

import java.util.*
import java.util.concurrent.LinkedBlockingQueue
import javax.swing.text.Position

@ModuleInfo(name = "GrimVelocity", description = "Grim", Chinese = "",category = ModuleCategory.COMBAT)
class GrimVelocity2: Module() {

    private var S08 = 0
    private var isvel = false


    override fun onEnable() {
        if (mc.thePlayer == null) return

    }
    override fun onDisable(){
        if (mc.thePlayer == null) return
    }
    @EventTarget
    fun onMotion(event: MotionEvent) {
        if (event.eventState == EventState.PRE && isvel) {
            isvel = false
            val blockPos = BlockPos(mc2.player.posX, mc2.player.posY, mc2.player.posZ)
            mc2.connection!!.sendPacket(
                CPacketPlayerDigging(
                    CPacketPlayerDigging.Action.STOP_DESTROY_BLOCK,
                    blockPos,
                    EnumFacing.NORTH
                )
            )
        }
    }

    @EventTarget
    fun onPacket(event: PacketEvent){

        val packet = event.packet.unwrap()

        if(S08>0){
            S08--
            return
        }

        if(packet is SPacketPlayerPosLook){
            S08 = 10

        }

        if (packet is SPacketEntityVelocity) {
            event.cancelEvent()

            isvel = true
        }

    }


}`
