### ISSUE TITLE
Add a new Velocity mod "HuaYuTing" form .kt

### ISSUE THREAD

**Issue by Genius114514** [SkidderMC/FDPClient#970]
We want to use your client on 1.12.2 Huayuting China's largest server, and we have to admit that your client has a good package break, but just a few weeks ago Huayuting updated his anti-cheat, causing the grim velocity mode to fail in the empty island war. This is the latest Velocity code to help you transcode, why choose your client? Because your client has a good 100% ab, this gives me a good edge in hvh
this is the code 

import net.ccbluex.liquidbounce.event.*
import net.ccbluex.liquidbounce.features.module.Module
import net.ccbluex.liquidbounce.features.module.ModuleCategory
import net.ccbluex.liquidbounce.features.module.ModuleInfo
import net.ccbluex.liquidbounce.injection.backend.unwrap
import net.ccbluex.liquidbounce.utils.ClientUtils
import net.ccbluex.liquidbounce.utils.MovementUtils
import net.ccbluex.liquidbounce.value.BoolValue
import net.ccbluex.liquidbounce.value.IntegerValue
import net.ccbluex.liquidbounce.value.ListValue
import net.minecraft.entity.EntityLivingBase
import net.minecraft.network.Packet
import net.minecraft.network.play.INetHandlerPlayClient
import net.minecraft.network.play.server.*
import net.minecraft.network.play.client.*
import net.minecraft.util.EnumFacing
import net.minecraft.util.math.BlockPos

import java.util.*
import java.util.concurrent.LinkedBlockingQueue
import javax.swing.text.Position

@ModuleInfo(name = "GrimVelocity", description = "Grim", Chinese = "",category = ModuleCategory.COMBAT)
class GrimVelocity2: Module() {

    private var S08 = 0
    private var isvel = false

    override fun onEnable() {
        if (mc.thePlayer == null) return

    }
    override fun onDisable(){
        if (mc.thePlayer == null) return
    }
    @EventTarget
    fun onMotion(event: MotionEvent) {
        if (event.eventState == EventState.PRE && isvel) {
            isvel = false
            val blockPos = BlockPos(mc2.player.posX, mc2.player.posY, mc2.player.posZ)
            mc2.connection!!.sendPacket(
                CPacketPlayerDigging(
                    CPacketPlayerDigging.Action.STOP_DESTROY_BLOCK,
                    blockPos,
                    EnumFacing.NORTH
                )
            )
        }
    }

    @EventTarget
    fun onPacket(event: PacketEvent){

        val packet = event.packet.unwrap()

        if(S08>0){
            S08--
            return
        }

        if(packet is SPacketPlayerPosLook){
            S08 = 10

        }

        if (packet is SPacketEntityVelocity) {
            event.cancelEvent()

            isvel = true
        }

    }

}

**Comment by Genius114514** [comment]
Error fixes the code was
package net.ccbluex.liquidbounce.features.module.modules.combat

import net.ccbluex.liquidbounce.event.*
import net.ccbluex.liquidbounce.features.module.Module
import net.ccbluex.liquidbounce.features.module.ModuleCategory
import net.ccbluex.liquidbounce.features.module.ModuleInfo
import net.ccbluex.liquidbounce.injection.backend.unwrap
import net.ccbluex.liquidbounce.utils.ClientUtils
import net.ccbluex.liquidbounce.utils.MovementUtils
import net.ccbluex.liquidbounce.value.BoolValue
import net.ccbluex.liquidbounce.value.IntegerValue
import net.ccbluex.liquidbounce.value.ListValue
import net.minecraft.entity.EntityLivingBase
import net.minecraft.network.Packet
import net.minecraft.network.play.INetHandlerPlayClient
import net.minecraft.network.play.server.*
import net.minecraft.network.play.client.*
import net.minecraft.util.EnumFacing
import net.minecraft.util.math.BlockPos

import java.util.*
import java.util.concurrent.LinkedBlockingQueue
import javax.swing.text.Position

@ModuleInfo(name = "GrimVelocity", description = "Grim", Chinese = "",category = ModuleCategory.COMBAT)
class GrimVelocity2: Module() {

    private var S08 = 0
    private var isvel = false


    override fun onEnable() {
        if (mc.thePlayer == null) return

    }
    override fun onDisable(){
        if (mc.thePlayer == null) return
    }
    @EventTarget
    fun onMotion(event: MotionEvent) {
        if (event.eventState == EventState.PRE && isvel) {
            isvel = false
            val blockPos = BlockPos(mc2.player.posX, mc2.player.posY, mc2.player.posZ)
            mc2.connection!!.sendPacket(
                CPacketPlayerDigging(
                    CPacketPlayerDigging.Action.STOP_DESTROY_BLOCK,
                    blockPos,
                    EnumFacing.NORTH
                )
            )
        }
    }

    @EventTarget
    fun onPacket(event: PacketEvent){

        val packet = event.packet.unwrap()

        if(S08>0){
            S08--
            return
        }

        if(packet is SPacketPlayerPosLook){
            S08 = 10

        }

        if (packet is SPacketEntityVelocity) {
            event.cancelEvent()

            isvel = true
        }

    }


}

**Comment by yfishyon** [comment]
if you have code, you can try building it yourself
在开挂小心药2暴打你

**Comment by ManInMyVan** [comment]
Readable version:
```kt
package net.ccbluex.liquidbounce.features.module.modules.combat

import net.ccbluex.liquidbounce.event.*
import net.ccbluex.liquidbounce.features.module.Module
import net.ccbluex.liquidbounce.features.module.ModuleCategory
import net.ccbluex.liquidbounce.features.module.ModuleInfo
import net.ccbluex.liquidbounce.injection.backend.unwrap
import net.ccbluex.liquidbounce.utils.ClientUtils
import net.ccbluex.liquidbounce.utils.MovementUtils
import net.ccbluex.liquidbounce.value.BoolValue
import net.ccbluex.liquidbounce.value.IntegerValue
import net.ccbluex.liquidbounce.value.ListValue
import net.minecraft.entity.EntityLivingBase
import net.minecraft.network.Packet
import net.minecraft.network.play.INetHandlerPlayClient
import net.minecraft.network.play.server.*
import net.minecraft.network.play.client.*
import net.minecraft.util.EnumFacing
import net.minecraft.util.math.BlockPos

import java.util.*
import java.util.concurrent.LinkedBlockingQueue
import javax.swing.text.Position

@ModuleInfo(name = "GrimVelocity", description = "Grim", Chinese = "",category = ModuleCategory.COMBAT)
class GrimVelocity2: Module() {

  private var S08 = 0
  private var isvel = false

  override fun onEnable() {
    if (mc.thePlayer == null) return
  }

  override fun onDisable() {
    if (mc.thePlayer == null) return
  }

  @EventTarget
  fun onMotion(event: MotionEvent) {
    if (event.eventState == EventState.PRE && isvel) {
      isvel = false
      val blockPos = BlockPos(mc2.player.posX, mc2.player.posY, mc2.player.posZ)
      mc2.connection!!.sendPacket(
        CPacketPlayerDigging(
          CPacketPlayerDigging.Action.STOP_DESTROY_BLOCK,
          blockPos,
          EnumFacing.NORTH
        )
      )
    }
  }

  @EventTarget
  fun onPacket(event: PacketEvent) {
  
    val packet = event.packet.unwrap()

    if (S08 > 0) {
      S08--
      return
    }

    if (packet is SPacketPlayerPosLook) {
      S08 = 10
    }

    if (packet is SPacketEntityVelocity) {
      event.cancelEvent()
      isvel = true
    }
  }
}
```
