### ISSUE TITLE
Idea for autoclickers algorithm

### ISSUE THREAD

**Issue by SmaamX** [SkidderMC/FDPClient#977]
I have an idea for auto clicking that might be able to bypass some detection algorithms +Simulation of shake

github.com/SmaamX/PyClickerX

**Comment by Saulildo** [comment]
Autoclicker detection algorithms suck and easy to bypass

**Comment by SmaamX** [comment]
> Autoclicker detection algorithms suck and easy to bypass

Only a better randomization would complete it
The number of clicks per second in a normal random algorithm has a different pattern each time
like this:
7, 13, 2, 17, 12, 1...
But with a slight difference, it can increase or decrease sinusoidally:
1, 2, 3, 5, 8, 12, 14, 12, 14, 15...
And in real human clicks, we have a short max time between multiple clicks or cooldowns and several other parameters (eg holding right click for 100ms or more/less between each click) so that future detection is 0%.
