### ISSUE TITLE
Can't join playpika server

### ISSUE THREAD

**Issue by kasperinjo** [SkidderMC/FDPClient#988]
Hey, playpika server is denying my login due to "the forbidden client" I am using. Can you please make a bypass for it?
play.pika-network.net

**Comment by BigPanda97** [comment]
Normally, they show this message when you join using a random generated username instead of a name which looks normal. And keep in mind that they also remember IP's, so when you have been flagged like this, you need to change your IP before changing the username.

**Comment by kasperinjo** [comment]
> Normally, they show this message when you join using a random generated username instead of a name which looks normal. And keep in mind that they also remember IP's, so when you have been flagged like this, you need to change your IP before changing the username.

Thanks! However, I tried a pretty normal name, "kasperinjo". Which one do you suggest?

**Comment by vPrah** [comment]
Try now with the latest version
