### ISSUE TITLE
Add grim speed for 1.12.2 severs from .kt

### ISSUE THREAD

**Issue by Genius785132** [SkidderMC/FDPClient#991]
High game version weak Entity Collision box check An Grim anti-cheat loophole,So we made a speed kt for 1.12.2 severs.If you use it, then you will have a speed of 10bps.
However, this code is based on the 1.12.2 liquidbounce client, so we need your transcoding support, thank you very much
Code:
`package net.ccbluex.liquidbounce.features.module.modules.movement

import net.ccbluex.liquidbounce.LiquidBounce
import net.ccbluex.liquidbounce.event.*
import net.ccbluex.liquidbounce.features.module.Module
import net.ccbluex.liquidbounce.features.module.ModuleCategory
import net.ccbluex.liquidbounce.features.module.ModuleInfo
import net.ccbluex.liquidbounce.utils.MovementUtils
import net.ccbluex.liquidbounce.utils.block.BlockUtils
import net.ccbluex.liquidbounce.utils.extensions.getDistanceToBox
import net.ccbluex.liquidbounce.utils.extensions.hitBox
import net.ccbluex.liquidbounce.utils.misc.FallingPlayer
import net.ccbluex.liquidbounce.utils.render.RenderUtils
import net.ccbluex.liquidbounce.value.BoolValue
import net.ccbluex.liquidbounce.value.FloatValue
import net.ccbluex.liquidbounce.value.IntegerValue
import net.ccbluex.liquidbounce.value.ListValue
import net.minecraft.block.BlockAir
import net.minecraft.client.renderer.GlStateManager
import net.minecraft.entity.EntityLivingBase
import net.minecraft.network.play.client.C03PacketPlayer
import net.minecraft.util.AxisAlignedBB
import net.minecraft.util.BlockPos
import org.lwjgl.opengl.GL11
import java.awt.Color
import kotlin.math.abs
import kotlin.math.floor
import kotlin.math.max

@ModuleInfo(name = "EntitySpeed", description = "", category = ModuleCategory.MOVEMENT)
class EntitySpeed : Module() {
    private val onlyAir = BoolValue("OnlyAir",false)
    private val okstrafe = BoolValue("Strafe",false)
    private val keepSprint = BoolValue("KeepSprint",false)
    private val speedUp = BoolValue("SpeedUp",false)
    private val speed = IntegerValue("Speed", 0, 0, 10)
    private val distance = FloatValue("Range", 0f, 0f, 1f)
    private var speeded = false
    private var pre = false
    var sprint = false

    override fun onEnable() {
        speeded = false
    }

    @EventTarget
    fun onUpdate(event: UpdateEvent) {
        val strafe = LiquidBounce.moduleManager.getModule(Strafe::class.java) as Strafe
        for (entity in mc.theWorld.loadedEntityList) {
            if (entity is EntityLivingBase && entity.entityId != mc.thePlayer.entityId && mc.thePlayer.getDistanceToBox(
                    entity.hitBox
                ) <= distance.get() && ( !onlyAir.get() || !mc.thePlayer.onGround)
            ) {
                if(speedUp.get()) {
                    mc.thePlayer.motionX *= (1 + (speed.get() * 0.01))
                    mc.thePlayer.motionZ *= (1 + (speed.get() * 0.01))
                }
                if(keepSprint.get()){
                    sprint = true
                }
                if(okstrafe.get()){
                    strafe.state = true
                }
                return
            }
            sprint = false
            strafe.state = false
        }
    }

}`

**Comment by ManInMyVan** [comment]
Tip: you can use 
\```kt
...
```
